// SPDX-License-Identifier: Apache-2.0
//! Floorplan write path — the primitives `vyges-ifp` composes.
//!
//! These are the odb calls upstream's `initialize_floorplan` makes: set the die area, create
//! rows across the core, then replace the core area with what the rows actually cover. The
//! algorithm lives in the engine; what is checked here is only that each primitive reaches odb
//! and survives a read-back.
use vyges_opendb_lib as odb;

const FIXTURE: &str = "test/fixtures/counter.odb";

#[test]
fn die_and_core_area_round_trip() {
    let db = odb::open_db(FIXTURE).expect("read");
    odb::block_set_die_area(&db, 0, 0, 2_000_000, 2_000_000).unwrap();
    assert_eq!(odb::block_get_die_area_x_min(&db), 0);
    assert_eq!(odb::block_get_die_area_x_max(&db), 2_000_000);
    assert_eq!(odb::block_get_die_area_y_max(&db), 2_000_000);

    odb::block_set_core_area(&db, 10_000, 20_000, 1_990_000, 1_980_000).unwrap();
    assert_eq!(odb::block_get_core_area_x_min(&db), 10_000);
    assert_eq!(odb::block_get_core_area_y_min(&db), 20_000);
    assert_eq!(odb::block_get_core_area_x_max(&db), 1_990_000);
}

#[test]
fn a_site_reports_its_size_and_an_unknown_one_reports_nothing() {
    let db = odb::open_db(FIXTURE).expect("read");
    assert!(
        odb::num_sites(&db).unwrap() > 0,
        "the fixture's library defines sites"
    );
    let site = first_site(&db).expect("a site");
    // Width/height/hybrid come from the GENERATED by-name accessors — no shim needed, and
    // adding one would have duplicated the schema-generated surface.
    let (w, h) = (
        odb::site_get_width(&db, &site),
        odb::site_get_height(&db, &site),
    );
    assert!(w > 0 && h > 0, "site {site} has zero extent: {w} x {h}");
    assert!(
        !odb::site_is_hybrid(&db, "no_such_site_xyz"),
        "unknown site is not hybrid"
    );
}

#[test]
fn rows_can_be_created_cleared_and_recreated() {
    // `initialize_floorplan` clears existing rows before rebuilding them, so both directions
    // have to work — and clearing has to report how many it removed.
    let db = odb::open_db(FIXTURE).expect("read");
    let site = first_site(&db).expect("site");
    let (site_dx, site_dy) = (
        odb::site_get_width(&db, &site),
        odb::site_get_height(&db, &site),
    );

    odb::clear_rows(&db).unwrap();
    assert_eq!(odb::num_rows(&db).unwrap(), 0, "cleared");

    odb::block_set_die_area(&db, 0, 0, site_dx * 100, site_dy * 10).unwrap();
    for r in 0..4 {
        let orient = if r % 2 == 0 { "R0" } else { "MX" };
        odb::row_create(
            &db,
            &format!("ROW_{r}"),
            &site,
            0,
            r * site_dy,
            orient,
            "HORIZONTAL",
            50,
            site_dx,
        )
        .unwrap();
    }
    assert_eq!(odb::num_rows(&db).unwrap(), 4);

    let removed = odb::clear_rows(&db).unwrap();
    assert_eq!(removed, 4, "clear_rows reports what it removed");
    assert_eq!(odb::num_rows(&db).unwrap(), 0);
}

#[test]
fn the_core_area_can_be_derived_from_the_rows() {
    // Upstream's `setCoreArea(computeCoreArea())` — the rule that makes the reported core area
    // what the rows COVER rather than what was asked for.
    let db = odb::open_db(FIXTURE).expect("read");
    let site = first_site(&db).expect("site");
    let (site_dx, site_dy) = (
        odb::site_get_width(&db, &site),
        odb::site_get_height(&db, &site),
    );
    let (x0, y0, n_sites, n_rows) = (1_000, 2_000, 40, 5);

    odb::clear_rows(&db).unwrap();
    odb::block_set_die_area(&db, 0, 0, x0 + site_dx * 1000, y0 + site_dy * 100).unwrap();
    for r in 0..n_rows {
        odb::row_create(
            &db,
            &format!("R{r}"),
            &site,
            x0,
            y0 + r * site_dy,
            "R0",
            "HORIZONTAL",
            n_sites,
            site_dx,
        )
        .unwrap();
    }

    // Computing must not store: two calls in a row give the same answer.
    let c = odb::block_compute_core_area(&db).unwrap();
    assert_eq!(c.len(), 4, "[x_min, y_min, x_max, y_max]");
    assert_eq!(c, odb::block_compute_core_area(&db).unwrap());
    assert_eq!((c[0], c[1]), (x0, y0), "lower left is where the rows start");
    assert_eq!(
        c[2],
        x0 + n_sites * site_dx,
        "upper right is where the sites end"
    );
    assert_eq!(c[3], y0 + n_rows * site_dy);

    // ...and storing it makes the block agree.
    odb::block_set_core_area_from_rows(&db).unwrap();
    assert_eq!(odb::block_get_core_area_x_min(&db), c[0]);
    assert_eq!(odb::block_get_core_area_x_max(&db), c[2]);
    assert_eq!(odb::block_get_core_area_y_max(&db), c[3]);

    // With no rows there is nothing to compute, and that is an empty answer rather than a guess.
    odb::clear_rows(&db).unwrap();
    assert!(odb::block_compute_core_area(&db).unwrap().is_empty());
}

#[test]
fn the_manufacturing_grid_is_readable_or_honestly_absent() {
    // 0 means "the tech declares none", which is the no-snap case in the ifp spec (R1) — not
    // an error, and not a silent 1.
    let db = odb::open_db(FIXTURE).expect("read");
    let grid = odb::tech_manufacturing_grid(&db).unwrap();
    assert!(
        grid >= 0,
        "grid is a DBU length or 0 for absent, got {grid}"
    );
}

#[test]
fn creating_a_row_on_an_unknown_site_fails_rather_than_inventing_one() {
    let db = odb::open_db(FIXTURE).expect("read");
    let err = odb::row_create(
        &db,
        "ROW_X",
        "no_such_site_xyz",
        0,
        0,
        "R0",
        "HORIZONTAL",
        1,
        1,
    );
    assert!(
        err.is_err(),
        "an unknown site must be an error, not a no-op"
    );
}

/// The first site the fixture's libraries define — discovered, never guessed.
fn first_site(db: &cxx::UniquePtr<odb::OdbDb>) -> Option<String> {
    (0..odb::num_sites(db).ok()?)
        .filter_map(|i| odb::nth_site_name(db, i).ok())
        .find(|n| !n.is_empty())
}

#[test]
fn a_plain_site_has_no_row_pattern_and_says_so_rather_than_erroring() {
    // Absence is an answer: length 0, not a throw. The engine asks this of every site to decide
    // between the uniform and hybrid paths, so it must be cheap and total.
    let db = odb::open_db(FIXTURE).expect("read");
    let site = first_site(&db).expect("a site");
    assert!(
        !odb::site_has_row_pattern(&db, &site),
        "the fixture's sites are plain"
    );
    assert_eq!(odb::site_row_pattern_len(&db, &site).unwrap(), 0);
    assert_eq!(
        odb::site_row_pattern_len(&db, "no_such_site_xyz").unwrap(),
        0
    );

    // Indexing a pattern that is not there is an error, not an empty string that would read as
    // a real site named "".
    assert!(odb::site_row_pattern_site(&db, &site, 0).is_err());
    assert!(odb::site_row_pattern_orient(&db, &site, 0).is_err());
}

#[test]
fn rows_are_cut_around_a_blockage_and_an_unknown_one_is_refused() {
    // Row cutting is odb's own algorithm; what is checked here is that the bridge reaches it and
    // that the blockage list is resolved by name rather than silently ignored.
    let db = odb::open_db(FIXTURE).expect("read");
    let site = first_site(&db).expect("site");
    let (w, h) = (
        odb::site_get_width(&db, &site),
        odb::site_get_height(&db, &site),
    );

    odb::clear_rows(&db).unwrap();
    odb::block_set_die_area(&db, 0, 0, w * 400, h * 8).unwrap();
    for r in 0..4 {
        odb::row_create(
            &db,
            &format!("R{r}"),
            &site,
            0,
            r * h,
            "R0",
            "HORIZONTAL",
            300,
            w,
        )
        .unwrap();
    }
    let before = odb::num_rows(&db).unwrap();

    // No blockages: nothing to cut around, so the row count cannot fall.
    odb::block_cut_rows(&db, 0, &[], 0, 0).unwrap();
    assert_eq!(odb::num_rows(&db).unwrap(), before, "no blockage, no cut");

    // A name the block does not define is an error -- cutting around nothing would look like
    // success and leave rows crossing a macro.
    assert!(odb::block_cut_rows(&db, 0, &["no_such_inst_xyz".to_string()], 0, 0).is_err());

    // A real instance cuts the rows it overlaps into pieces, so the count RISES.
    let inst = odb::nth_inst_name(&db, 0);
    assert!(!inst.is_empty(), "the fixture has instances");
    odb::block_cut_rows(&db, 0, std::slice::from_ref(&inst), 0, 0).unwrap();
    assert!(
        odb::num_rows(&db).unwrap() >= before,
        "cutting splits rows in two around the macro, it never loses them silently"
    );
}

#[test]
fn the_one_site_master_question_is_answerable() {
    // Drives whether tapcells may leave one-site gaps; it must be a plain answer, not an error.
    let db = odb::open_db(FIXTURE).expect("read");
    let _: bool = odb::has_one_site_master(&db);
}

#[test]
fn rows_can_be_enumerated_and_their_sites_classified() {
    // row_get_* address a row by name; without this the names cannot be discovered at all, and a
    // floorplan's row names are not predictable enough to guess.
    let db = odb::open_db(FIXTURE).expect("read");
    let site = first_site(&db).expect("site");
    odb::clear_rows(&db).unwrap();
    let (w, h) = (
        odb::site_get_width(&db, &site),
        odb::site_get_height(&db, &site),
    );
    odb::block_set_die_area(&db, 0, 0, w * 100, h * 4).unwrap();
    for r in 0..3 {
        odb::row_create(
            &db,
            &format!("R{r}"),
            &site,
            0,
            r * h,
            "R0",
            "HORIZONTAL",
            50,
            w,
        )
        .unwrap();
    }

    let names: Vec<String> = (0..odb::num_rows(&db).unwrap())
        .map(|i| odb::nth_row_name(&db, i).unwrap())
        .collect();
    // odb hands rows back in REVERSE creation order. Pinned rather than sorted away: anything
    // that numbers or iterates rows (tapcell naming, for one) inherits this order, and a future
    // change to it would otherwise show up as a mystery diff in a golden.
    assert_eq!(names, vec!["R2", "R1", "R0"], "reverse creation order");
    assert!(
        odb::nth_row_name(&db, 99).unwrap().is_empty(),
        "out of range is empty, not an error"
    );

    // The class is what separates core rows from pad rows; it must be readable and honest.
    let class = odb::site_get_class(&db, &site).unwrap();
    assert!(!class.is_empty(), "a site states its class");
    assert!(odb::site_get_class(&db, "no_such_site_xyz")
        .unwrap()
        .is_empty());
}
