#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Summarise the two coverage maps (docs/derived-{core,full}-schema.json) as Markdown.

Writes docs/coverage-summary.md (committed, so check-generated.sh's freshness gate fails when the
maps move and the summary was not regenerated). With --block FILE (repeatable), it also rewrites
the region between the markers

    <!-- coverage-summary:begin -->
    <!-- coverage-summary:end -->

in each FILE, so a document elsewhere can carry the current numbers without hand copying. A FILE
without both markers is an error: a silently skipped block is a stale block.

The summary carries no date or commit, so it changes only when the coverage does.
"""
import argparse
import collections
import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
READ_KINDS = ("getter", "predicate", "iterator", "relation")
BEGIN, END = "<!-- coverage-summary:begin -->", "<!-- coverage-summary:end -->"


def load(name):
    d = json.load(open(os.path.join(HERE, "docs", f"derived-{name}-schema.json")))
    cl = d["classes"]
    items = list(cl.items()) if isinstance(cl, dict) else [(c["name"], c) for c in cl]
    return d, items


def pct(a, b):
    return f"{100.0 * a / b:.1f}%" if b else "-"


def stats(items):
    total, bound = collections.Counter(), collections.Counter()
    per_class = []
    for name, c in items:
        n = len(c["methods"])
        b = sum(1 for m in c["methods"] if m.get("bridged"))
        per_class.append((n - b, name, n))
        for m in c["methods"]:
            total[m["kind"]] += 1
            bound[m["kind"]] += bool(m.get("bridged"))
    return total, bound, per_class


def summary():
    lines = [
        "| Map | Classes | Methods | Bound | Not covered |",
        "| --- | --- | --- | --- | --- |",
    ]
    kinds = []
    gaps = None
    for name, label in (("core", "Core (hand-written classes; the headline metric)"), ("full", "Full (every class with a schema)")):
        d, items = load(name)
        m, b = d["method_count"], d["bridged_count"]
        lines.append(f"| {label} | {d['class_count']} | {m:,} | {b:,} ({pct(b, m)}) | **{m - b:,} ({pct(m - b, m)})** |")
        total, bound, per_class = stats(items)
        rt = sum(total[k] for k in READ_KINDS)
        rb = sum(bound[k] for k in READ_KINDS)
        parts = ", ".join(f"{k}s {bound[k]}/{total[k]}" for k in READ_KINDS)
        kinds.append(
            f"- **{name}:** read side {rb:,}/{rt:,} ({pct(rb, rt)}): {parts}; setters "
            f"{bound['setter']:,}/{total['setter']:,} ({pct(bound['setter'], total['setter'])}); other "
            f"{bound['other']}/{total['other']}."
        )
        if name == "core":
            gaps = sorted((x for x in per_class if x[0]), key=lambda x: (-x[0], x[1]))[:10]
    lines += ["", "By kind:", ""] + kinds
    lines += ["", "Largest gaps (core; unbound of total):", ""]
    lines.append(" · ".join(f"`{n}` {u}/{t}" for u, n, t in gaps))
    return "\n".join(lines) + "\n"


def rewrite_block(path, body):
    t = open(path).read()
    if t.count(BEGIN) != 1 or t.count(END) != 1 or t.index(BEGIN) > t.index(END):
        sys.exit(f"{path}: needs exactly one {BEGIN} ... {END} region")
    i = t.index(BEGIN) + len(BEGIN)
    j = t.index(END)
    new = t[:i] + "\n" + body + t[j:]
    if new != t:
        open(path, "w").write(new)
        print(f"updated {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--block", action="append", default=[], help="also rewrite the marked region in this file")
    a = ap.parse_args()
    body = summary()
    out = os.path.join(HERE, "docs", "coverage-summary.md")
    head = (
        "# Binding coverage summary\n\n"
        "Generated by `scripts/coverage-summary.py` from `derived-core-schema.json` and\n"
        "`derived-full-schema.json`; `scripts/check-generated.sh` regenerates it. Do not edit by hand.\n\n"
        "A method not bound answers `unimplemented` when called, so a gap is reported when a caller\n"
        "needs it. Most of what is unbound is write methods outside the generated read surface.\n\n"
    )
    open(out, "w").write(head + body)
    for f in a.block:
        rewrite_block(f, body)


if __name__ == "__main__":
    main()
