// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
//! Third cxx bridge: machine-generated SETTERS (the L2/write governance surface).
//! Gated behind the `gen-write` feature — absent from the default read-only build.

#[cxx::bridge]
mod ffi_gen_write {
    unsafe extern "C++" {
        include!("generated_write.h");
        type OdbDb = crate::ffi::OdbDb;
        fn block_clear_global_connect(db: &OdbDb) -> Result<()>;
        fn block_set_corner_name_list(db: &OdbDb, name_list: &str) -> Result<()>;
        fn block_set_corner_count(db: &OdbDb, corner_cnt: i32, ext_db_cnt: i32, name_list: &str) -> Result<()>;
        fn block_set_min_routing_layer(db: &OdbDb, min_routing_layer: i32) -> Result<()>;
        fn block_set_max_routing_layer(db: &OdbDb, max_routing_layer: i32) -> Result<()>;
        fn block_set_min_layer_for_clock(db: &OdbDb, min_layer_for_clock: i32) -> Result<()>;
        fn block_set_max_layer_for_clock(db: &OdbDb, max_layer_for_clock: i32) -> Result<()>;
        fn block_clear(db: &OdbDb) -> Result<()>;
        fn block_set_driving_itermsfor_nets(db: &OdbDb) -> Result<()>;
        fn block_clear_user_inst_flags(db: &OdbDb) -> Result<()>;
        fn inst_set_origin(db: &OdbDb, inst: &str, x: i32, y: i32) -> Result<()>;
        fn inst_set_orient(db: &OdbDb, inst: &str, orient: &str) -> Result<()>;
        fn inst_set_location(db: &OdbDb, inst: &str, x: i32, y: i32) -> Result<()>;
        fn inst_set_location_orient(db: &OdbDb, inst: &str, orient: &str) -> Result<()>;
        fn inst_set_placement_status(db: &OdbDb, inst: &str, status: &str) -> Result<()>;
        fn inst_set_eco_create(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_eco_destroy(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_eco_modify(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_user_flag1(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_clear_user_flag1(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_set_user_flag2(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_clear_user_flag2(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_set_user_flag3(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_clear_user_flag3(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_set_do_not_touch(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_halo(db: &OdbDb, inst: &str, left: i32, bottom: i32, right: i32, top: i32, is_soft: bool) -> Result<()>;
        fn inst_set_weight(db: &OdbDb, inst: &str, weight: i32) -> Result<()>;
        fn inst_set_source_type(db: &OdbDb, inst: &str, a0: &str) -> Result<()>;
        fn inst_set_pin_access_idx(db: &OdbDb, inst: &str, idx: u32) -> Result<()>;
        fn net_set_r_c_disconnected(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_weight(db: &OdbDb, net: &str, weight: i32) -> Result<()>;
        fn net_set_source_type(db: &OdbDb, net: &str, a0: &str) -> Result<()>;
        fn net_set_x_talk_class(db: &OdbDb, net: &str, value: i32) -> Result<()>;
        fn net_set_fixed_bump(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_wire_type(db: &OdbDb, net: &str, wire_type: &str) -> Result<()>;
        fn net_set_sig_type(db: &OdbDb, net: &str, sig_type: &str) -> Result<()>;
        fn net_set_mark(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_mark_1(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_select(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_wire_ordered(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_disconnected(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_wire_altered(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_r_cgraph(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_extracted(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_spef(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_do_not_touch(db: &OdbDb, net: &str, v: bool) -> Result<()>;
        fn net_set_special(db: &OdbDb, net: &str) -> Result<()>;
        fn net_clear_special(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_i_oflag(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_wild_connected(db: &OdbDb, net: &str) -> Result<()>;
        fn net_clear_wild_connected(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_gndc_calib_factor(db: &OdbDb, net: &str, gndc_calib: f32) -> Result<()>;
        fn net_set_cc_calib_factor(db: &OdbDb, net: &str, cc_calib: f32) -> Result<()>;
        fn net_set_cc_adjust_factor(db: &OdbDb, net: &str, factor: f32) -> Result<()>;
        fn net_set_cc_adjust_order(db: &OdbDb, net: &str, order: u32) -> Result<()>;
        fn net_set_db_cc(db: &OdbDb, net: &str, cap: f32) -> Result<()>;
        fn net_set_ref_cc(db: &OdbDb, net: &str, cap: f32) -> Result<()>;
        fn net_set_cc_match_ratio(db: &OdbDb, net: &str, ratio: f32) -> Result<()>;
        fn net_set1st_r_seg_id(db: &OdbDb, net: &str, rseg_id: u32) -> Result<()>;
        fn net_set1st_cap_node_id(db: &OdbDb, net: &str, capn_id: u32) -> Result<()>;
        fn net_set_term_ext_ids(db: &OdbDb, net: &str, cap_id: i32) -> Result<()>;
        fn net_set_non_default_rule(db: &OdbDb, net: &str, rule: &str) -> Result<()>;
        fn net_clear_guides(db: &OdbDb, net: &str) -> Result<()>;
        fn net_clear_tracks(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_jumpers(db: &OdbDb, net: &str, has_jumpers: bool) -> Result<()>;
        fn net_set_auto_taper(db: &OdbDb, net: &str, enable: bool) -> Result<()>;
        fn bterm_set_sig_type(db: &OdbDb, bterm: &str, a0: &str) -> Result<()>;
        fn bterm_set_spef_mark(db: &OdbDb, bterm: &str, v: u32) -> Result<()>;
        fn bterm_set_mark(db: &OdbDb, bterm: &str, v: u32) -> Result<()>;
        fn bterm_set_ext_id(db: &OdbDb, bterm: &str, v: u32) -> Result<()>;
        fn bterm_set_special(db: &OdbDb, bterm: &str) -> Result<()>;
        fn bterm_set_ground_pin(db: &OdbDb, bterm: &str, pin: &str) -> Result<()>;
        fn bterm_set_supply_pin(db: &OdbDb, bterm: &str, pin: &str) -> Result<()>;
        fn bterm_set_mirrored_b_term(db: &OdbDb, bterm: &str, mirrored_bterm: &str) -> Result<()>;
        fn master_set_origin(db: &OdbDb, master: &str, x: i32, y: i32) -> Result<()>;
        fn master_set_width(db: &OdbDb, master: &str, width: u32) -> Result<()>;
        fn master_set_height(db: &OdbDb, master: &str, height: u32) -> Result<()>;
        fn master_set_backside_bridge(db: &OdbDb, master: &str, is_bridge: bool) -> Result<()>;
        fn master_set_l_e_q(db: &OdbDb, master: &str, a0: &str) -> Result<()>;
        fn master_set_e_e_q(db: &OdbDb, master: &str, a0: &str) -> Result<()>;
        fn master_set_symmetry_x(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_symmetry_y(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_symmetry_r90(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_frozen(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_sequential(db: &OdbDb, master: &str, v: bool) -> Result<()>;
        fn master_set_mark(db: &OdbDb, master: &str, mark: u32) -> Result<()>;
        fn master_set_special_power(db: &OdbDb, master: &str, v: bool) -> Result<()>;
        fn master_set_site(db: &OdbDb, master: &str, site: &str) -> Result<()>;
        fn master_clear_pin_access(db: &OdbDb, master: &str, pin_access_idx: i32) -> Result<()>;
        fn iterm_set_spef(db: &OdbDb, inst: &str, pin: &str, v: u32) -> Result<()>;
        fn iterm_set_ext_id(db: &OdbDb, inst: &str, pin: &str, v: u32) -> Result<()>;
        fn iterm_set_special(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_clear_special(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_set_clocked(db: &OdbDb, inst: &str, pin: &str, v: bool) -> Result<()>;
        fn iterm_set_mark(db: &OdbDb, inst: &str, pin: &str, v: u32) -> Result<()>;
        fn iterm_set_connected(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_clear_connected(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_clear_pref_access_points(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn mterm_set_sig_type(db: &OdbDb, master: &str, term: &str, a0: &str) -> Result<()>;
        fn mterm_set_mark(db: &OdbDb, master: &str, term: &str, v: u32) -> Result<()>;
        fn layer_set_wrong_way_width(db: &OdbDb, layer: &str, wrong_way_width: u32) -> Result<()>;
        fn layer_set_wrong_way_min_width(db: &OdbDb, layer: &str, wrong_way_min_width: u32) -> Result<()>;
        fn layer_set_layer_adjustment(db: &OdbDb, layer: &str, layer_adjustment: f32) -> Result<()>;
        fn layer_set_rect_only(db: &OdbDb, layer: &str, rect_only: bool) -> Result<()>;
        fn layer_set_right_way_on_grid_only(db: &OdbDb, layer: &str, right_way_on_grid_only: bool) -> Result<()>;
        fn layer_set_right_way_on_grid_only_check_mask(db: &OdbDb, layer: &str, right_way_on_grid_only_check_mask: bool) -> Result<()>;
        fn layer_set_rect_only_except_non_core_pins(db: &OdbDb, layer: &str, rect_only_except_non_core_pins: bool) -> Result<()>;
        fn layer_set_backside(db: &OdbDb, layer: &str, is_backside: bool) -> Result<()>;
        fn layer_set_alias(db: &OdbDb, layer: &str, alias: &str) -> Result<()>;
        fn layer_set_width(db: &OdbDb, layer: &str, width: i32) -> Result<()>;
        fn layer_set_spacing(db: &OdbDb, layer: &str, spacing: i32) -> Result<()>;
        fn layer_set_num_masks(db: &OdbDb, layer: &str, number: u32) -> Result<()>;
        fn layer_set_pitch(db: &OdbDb, layer: &str, pitch: i32) -> Result<()>;
        fn layer_set_pitch_x_y(db: &OdbDb, layer: &str, pitch_x: i32, pitch_y: i32) -> Result<()>;
        fn layer_set_first_last_pitch(db: &OdbDb, layer: &str, first_last_pitch: i32) -> Result<()>;
        fn layer_set_offset(db: &OdbDb, layer: &str, pitch: i32) -> Result<()>;
        fn layer_set_offset_x_y(db: &OdbDb, layer: &str, pitch_x: i32, pitch_y: i32) -> Result<()>;
        fn layer_set_thickness(db: &OdbDb, layer: &str, thickness: u32) -> Result<()>;
        fn layer_set_area(db: &OdbDb, layer: &str, area: i64) -> Result<()>;
        fn layer_set_max_width(db: &OdbDb, layer: &str, max_width: u32) -> Result<()>;
        fn layer_set_min_width(db: &OdbDb, layer: &str, max_width: u32) -> Result<()>;
        fn layer_set_min_step(db: &OdbDb, layer: &str, min_step: u32) -> Result<()>;
        fn layer_set_min_step_max_length(db: &OdbDb, layer: &str, length: u32) -> Result<()>;
        fn layer_set_min_step_max_edges(db: &OdbDb, layer: &str, edges: u32) -> Result<()>;
        fn layer_set_protrusion(db: &OdbDb, layer: &str, pt_width: u32, pt_length: u32, pt_from_width: u32) -> Result<()>;
        fn layer_set_resistance(db: &OdbDb, layer: &str, res: f64) -> Result<()>;
        fn layer_set_capacitance(db: &OdbDb, layer: &str, cap: f64) -> Result<()>;
        fn layer_set_edge_capacitance(db: &OdbDb, layer: &str, cap: f64) -> Result<()>;
        fn layer_set_wire_extension(db: &OdbDb, layer: &str, ext: u32) -> Result<()>;
        fn via_set_pattern(db: &OdbDb, via: &str, pattern: &str) -> Result<()>;
        fn techvia_set_default(db: &OdbDb, via: &str) -> Result<()>;
        fn techvia_set_top_of_stack(db: &OdbDb, via: &str) -> Result<()>;
        fn techvia_set_resistance(db: &OdbDb, via: &str, res: f64) -> Result<()>;
        fn techvia_set_pattern(db: &OdbDb, via: &str, pattern: &str) -> Result<()>;
        fn ndr_set_hard_spacing(db: &OdbDb, rule: &str, value: bool) -> Result<()>;
        fn ndr_set_min_cuts(db: &OdbDb, rule: &str, cut_layer: &str, count: i32) -> Result<()>;
        fn site_set_width(db: &OdbDb, site: &str, width: i32) -> Result<()>;
        fn site_set_height(db: &OdbDb, site: &str, height: i32) -> Result<()>;
        fn site_set_symmetry_x(db: &OdbDb, site: &str) -> Result<()>;
        fn site_set_symmetry_y(db: &OdbDb, site: &str) -> Result<()>;
        fn site_set_symmetry_r90(db: &OdbDb, site: &str) -> Result<()>;
        fn obs_set_slot_obstruction(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_fill_obstruction(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_except_p_g_nets_obstruction(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_pushed_down(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_effective_width(db: &OdbDb, idx: usize, w: i32) -> Result<()>;
        fn obs_set_min_spacing(db: &OdbDb, idx: usize, w: i32) -> Result<()>;
        fn obs_set_is_system_reserved(db: &OdbDb, idx: usize, is_system_reserved: bool) -> Result<()>;
        fn swire_set_wire_type(db: &OdbDb, net: &str, idx: usize, a0: &str) -> Result<()>;
        fn guide_set_is_jumper(db: &OdbDb, net: &str, idx: usize, jumper: bool) -> Result<()>;
        fn guide_set_is_connected_to_term(db: &OdbDb, net: &str, idx: usize, is_connected: bool) -> Result<()>;
        fn gcell_set_capacity(db: &OdbDb, layer: &str, x_idx: u32, y_idx: u32, capacity: f32) -> Result<()>;
        fn gcell_set_usage(db: &OdbDb, layer: &str, x_idx: u32, y_idx: u32, a3: f32) -> Result<()>;
        fn wire_set_property(db: &OdbDb, net: &str, jid: i32, property: i32) -> Result<()>;
        fn box_set_soft(db: &OdbDb, idx: usize, value: bool) -> Result<()>;
        fn box_set_layer_mask(db: &OdbDb, idx: usize, mask: u32) -> Result<()>;
        fn module_set_mod_inst(db: &OdbDb, module: &str, mod_inst: &str) -> Result<()>;
        fn region_set_invalid(db: &OdbDb, region: &str, v: bool) -> Result<()>;
        fn blockage_set_pushed_down(db: &OdbDb, idx: usize) -> Result<()>;
        fn blockage_set_soft(db: &OdbDb, idx: usize) -> Result<()>;
        fn blockage_set_is_system_reserved(db: &OdbDb, idx: usize, is_system_reserved: bool) -> Result<()>;
        fn blockage_set_max_density(db: &OdbDb, idx: usize, max_density: f32) -> Result<()>;
        fn marker_cat_set_description(db: &OdbDb, category: &str, description: &str) -> Result<()>;
        fn marker_cat_set_source(db: &OdbDb, category: &str, source: &str) -> Result<()>;
        fn marker_cat_set_max_markers(db: &OdbDb, category: &str, max_markers: i32) -> Result<()>;
        fn marker_set_comment(db: &OdbDb, category: &str, idx: usize, comment: &str) -> Result<()>;
        fn marker_set_line_number(db: &OdbDb, category: &str, idx: usize, line_number: i32) -> Result<()>;
        fn marker_set_visited(db: &OdbDb, category: &str, idx: usize, visited: bool) -> Result<()>;
        fn marker_set_visible(db: &OdbDb, category: &str, idx: usize, visible: bool) -> Result<()>;
        fn marker_set_waived(db: &OdbDb, category: &str, idx: usize, waived: bool) -> Result<()>;
        fn marker_set_tech_layer(db: &OdbDb, category: &str, idx: usize, layer: &str) -> Result<()>;
        fn modbterm_set_mod_net(db: &OdbDb, module: &str, idx: usize, mod_net: &str) -> Result<()>;
        fn moditerm_set_mod_net(db: &OdbDb, modinst: &str, idx: usize, mod_net: &str) -> Result<()>;
        fn pwr_domain_set_top(db: &OdbDb, name: &str, top: bool) -> Result<()>;
        fn pwr_domain_set_parent(db: &OdbDb, name: &str, parent: &str) -> Result<()>;
        fn pwr_domain_set_voltage(db: &OdbDb, name: &str, voltage: f32) -> Result<()>;
        fn pwr_domain_set_group(db: &OdbDb, name: &str, group: &str) -> Result<()>;
        fn pwr_switch_set_power_domain(db: &OdbDb, name: &str, power_domain: &str) -> Result<()>;
        fn pwr_switch_set_out_supply_port(db: &OdbDb, name: &str, out_port: &str, net: &str) -> Result<()>;
        fn pwr_switch_set_lib_cell(db: &OdbDb, name: &str, master: &str) -> Result<()>;
        fn isolation_set_applies_to(db: &OdbDb, name: &str, applies_to: &str) -> Result<()>;
        fn isolation_set_clamp_value(db: &OdbDb, name: &str, clamp_value: &str) -> Result<()>;
        fn isolation_set_isolation_signal(db: &OdbDb, name: &str, isolation_signal: &str) -> Result<()>;
        fn isolation_set_isolation_sense(db: &OdbDb, name: &str, isolation_sense: &str) -> Result<()>;
        fn isolation_set_location(db: &OdbDb, name: &str, location: &str) -> Result<()>;
        fn isolation_set_power_domain(db: &OdbDb, name: &str, power_domain: &str) -> Result<()>;
        fn level_shifter_set_source(db: &OdbDb, name: &str, source: &str) -> Result<()>;
        fn level_shifter_set_sink(db: &OdbDb, name: &str, sink: &str) -> Result<()>;
        fn level_shifter_set_use_functional_equivalence(db: &OdbDb, name: &str, use_functional_equivalence: bool) -> Result<()>;
        fn level_shifter_set_applies_to(db: &OdbDb, name: &str, applies_to: &str) -> Result<()>;
        fn level_shifter_set_applies_to_boundary(db: &OdbDb, name: &str, applies_to_boundary: &str) -> Result<()>;
        fn level_shifter_set_rule(db: &OdbDb, name: &str, rule: &str) -> Result<()>;
        fn level_shifter_set_threshold(db: &OdbDb, name: &str, threshold: f32) -> Result<()>;
        fn level_shifter_set_no_shift(db: &OdbDb, name: &str, no_shift: bool) -> Result<()>;
        fn level_shifter_set_force_shift(db: &OdbDb, name: &str, force_shift: bool) -> Result<()>;
        fn level_shifter_set_location(db: &OdbDb, name: &str, location: &str) -> Result<()>;
        fn level_shifter_set_input_supply(db: &OdbDb, name: &str, input_supply: &str) -> Result<()>;
        fn level_shifter_set_output_supply(db: &OdbDb, name: &str, output_supply: &str) -> Result<()>;
        fn level_shifter_set_internal_supply(db: &OdbDb, name: &str, internal_supply: &str) -> Result<()>;
        fn level_shifter_set_name_prefix(db: &OdbDb, name: &str, name_prefix: &str) -> Result<()>;
        fn level_shifter_set_name_suffix(db: &OdbDb, name: &str, name_suffix: &str) -> Result<()>;
        fn level_shifter_set_cell_name(db: &OdbDb, name: &str, cell_name: &str) -> Result<()>;
        fn level_shifter_set_cell_input(db: &OdbDb, name: &str, cell_input: &str) -> Result<()>;
        fn level_shifter_set_cell_output(db: &OdbDb, name: &str, cell_output: &str) -> Result<()>;
        fn tech_set_lef_units(db: &OdbDb, units: i32) -> Result<()>;
        fn tech_set_lef_version(db: &OdbDb, inver: f64) -> Result<()>;
        fn tech_set_manufacturing_grid(db: &OdbDb, ingrd: i32) -> Result<()>;
        fn lib_set_lef_units(db: &OdbDb, name: &str, units: i32) -> Result<()>;
        fn capnode_set_capacitance(db: &OdbDb, idx: usize, cap: f64, corner: i32) -> Result<()>;
        fn capnode_set_node(db: &OdbDb, idx: usize, nodeid: u32) -> Result<()>;
        fn capnode_set_select(db: &OdbDb, idx: usize, value: bool) -> Result<()>;
        fn capnode_set_children_cnt(db: &OdbDb, idx: usize, cnt: u32) -> Result<()>;
        fn capnode_set_name_flag(db: &OdbDb, idx: usize) -> Result<()>;
        fn capnode_set_b_term_flag(db: &OdbDb, idx: usize) -> Result<()>;
        fn capnode_set_i_term_flag(db: &OdbDb, idx: usize) -> Result<()>;
        fn capnode_set_internal_flag(db: &OdbDb, idx: usize) -> Result<()>;
        fn capnode_set_branch_flag(db: &OdbDb, idx: usize) -> Result<()>;
        fn capnode_set_foreign_flag(db: &OdbDb, idx: usize) -> Result<()>;
        fn capnode_set_sort_index(db: &OdbDb, idx: usize, a0: u32) -> Result<()>;
        fn capnode_set_net(db: &OdbDb, idx: usize, netid: u32) -> Result<()>;
        fn capnode_set_next(db: &OdbDb, idx: usize, nextid: u32) -> Result<()>;
        fn rseg_set_capacitance(db: &OdbDb, idx: usize, cap: f64, corner: i32) -> Result<()>;
        fn rseg_set_resistance(db: &OdbDb, idx: usize, res: f64, corner: i32) -> Result<()>;
        fn rseg_set_next(db: &OdbDb, idx: usize, next_id: u32) -> Result<()>;
        fn rseg_set_source_node(db: &OdbDb, idx: usize, nodeid: u32) -> Result<()>;
        fn rseg_set_target_node(db: &OdbDb, idx: usize, nodeid: u32) -> Result<()>;
        fn rseg_set_coords(db: &OdbDb, idx: usize, x: i32, y: i32) -> Result<()>;
        fn ccseg_set_capacitance(db: &OdbDb, idx: usize, cap: f64, corner: i32) -> Result<()>;
        fn ccseg_set_mark(db: &OdbDb, idx: usize, value: bool) -> Result<()>;
        fn sbox_set_via_layer_mask(db: &OdbDb, net: &str, swire_idx: usize, sbox_idx: usize, bottom: u32, cut: u32, top: u32) -> Result<()>;
        fn bpin_set_placement_status(db: &OdbDb, bterm: &str, idx: usize, status: &str) -> Result<()>;
        fn bpin_set_effective_width(db: &OdbDb, bterm: &str, idx: usize, w: i32) -> Result<()>;
        fn bpin_set_min_spacing(db: &OdbDb, bterm: &str, idx: usize, w: i32) -> Result<()>;
        fn mpin_clear_pin_access(db: &OdbDb, master: &str, term: &str, idx: usize, pin_access_idx: i32) -> Result<()>;
        fn techvialayerrule_set_width(db: &OdbDb, gen_idx: usize, layer_idx: usize, min_width: i32, max_width: i32) -> Result<()>;
        fn techvialayerrule_set_enclosure(db: &OdbDb, gen_idx: usize, layer_idx: usize, overhang1: i32, overhang2: i32) -> Result<()>;
        fn techvialayerrule_set_overhang(db: &OdbDb, gen_idx: usize, layer_idx: usize, overhang: i32) -> Result<()>;
        fn techvialayerrule_set_metal_overhang(db: &OdbDb, gen_idx: usize, layer_idx: usize, overhang: i32) -> Result<()>;
        fn techvialayerrule_set_spacing(db: &OdbDb, gen_idx: usize, layer_idx: usize, x_spacing: i32, y_spacing: i32) -> Result<()>;
        fn techvialayerrule_set_resistance(db: &OdbDb, gen_idx: usize, layer_idx: usize, r: f64) -> Result<()>;
        fn cutclassrule_set_width(db: &OdbDb, layer: &str, idx: usize, width: i32) -> Result<()>;
        fn cutclassrule_set_length(db: &OdbDb, layer: &str, idx: usize, length: i32) -> Result<()>;
        fn cutclassrule_set_num_cuts(db: &OdbDb, layer: &str, idx: usize, num_cuts: i32) -> Result<()>;
        fn cutclassrule_set_length_valid(db: &OdbDb, layer: &str, idx: usize, length_valid: bool) -> Result<()>;
        fn cutclassrule_set_cuts_valid(db: &OdbDb, layer: &str, idx: usize, cuts_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_eol_width(db: &OdbDb, layer: &str, idx: usize, eol_width: i32) -> Result<()>;
        fn cutenclosurerule_set_eol_min_length(db: &OdbDb, layer: &str, idx: usize, eol_min_length: i32) -> Result<()>;
        fn cutenclosurerule_set_first_overhang(db: &OdbDb, layer: &str, idx: usize, first_overhang: i32) -> Result<()>;
        fn cutenclosurerule_set_second_overhang(db: &OdbDb, layer: &str, idx: usize, second_overhang: i32) -> Result<()>;
        fn cutenclosurerule_set_spacing(db: &OdbDb, layer: &str, idx: usize, spacing: i32) -> Result<()>;
        fn cutenclosurerule_set_extension(db: &OdbDb, layer: &str, idx: usize, extension: i32) -> Result<()>;
        fn cutenclosurerule_set_forward_extension(db: &OdbDb, layer: &str, idx: usize, forward_extension: i32) -> Result<()>;
        fn cutenclosurerule_set_backward_extension(db: &OdbDb, layer: &str, idx: usize, backward_extension: i32) -> Result<()>;
        fn cutenclosurerule_set_min_width(db: &OdbDb, layer: &str, idx: usize, min_width: i32) -> Result<()>;
        fn cutenclosurerule_set_cut_within(db: &OdbDb, layer: &str, idx: usize, cut_within: i32) -> Result<()>;
        fn cutenclosurerule_set_min_length(db: &OdbDb, layer: &str, idx: usize, min_length: i32) -> Result<()>;
        fn cutenclosurerule_set_par_length(db: &OdbDb, layer: &str, idx: usize, par_length: i32) -> Result<()>;
        fn cutenclosurerule_set_second_par_length(db: &OdbDb, layer: &str, idx: usize, second_par_length: i32) -> Result<()>;
        fn cutenclosurerule_set_par_within(db: &OdbDb, layer: &str, idx: usize, par_within: i32) -> Result<()>;
        fn cutenclosurerule_set_second_par_within(db: &OdbDb, layer: &str, idx: usize, second_par_within: i32) -> Result<()>;
        fn cutenclosurerule_set_below_enclosure(db: &OdbDb, layer: &str, idx: usize, below_enclosure: i32) -> Result<()>;
        fn cutenclosurerule_set_num_corners(db: &OdbDb, layer: &str, idx: usize, num_corners: u32) -> Result<()>;
        fn cutenclosurerule_set_cut_class_valid(db: &OdbDb, layer: &str, idx: usize, cut_class_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_above(db: &OdbDb, layer: &str, idx: usize, above: bool) -> Result<()>;
        fn cutenclosurerule_set_below(db: &OdbDb, layer: &str, idx: usize, below: bool) -> Result<()>;
        fn cutenclosurerule_set_eol_min_length_valid(db: &OdbDb, layer: &str, idx: usize, eol_min_length_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_eol_only(db: &OdbDb, layer: &str, idx: usize, eol_only: bool) -> Result<()>;
        fn cutenclosurerule_set_short_edge_on_eol(db: &OdbDb, layer: &str, idx: usize, short_edge_on_eol: bool) -> Result<()>;
        fn cutenclosurerule_set_side_spacing_valid(db: &OdbDb, layer: &str, idx: usize, side_spacing_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_end_spacing_valid(db: &OdbDb, layer: &str, idx: usize, end_spacing_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_off_center_line(db: &OdbDb, layer: &str, idx: usize, off_center_line: bool) -> Result<()>;
        fn cutenclosurerule_set_width_valid(db: &OdbDb, layer: &str, idx: usize, width_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_include_abutted(db: &OdbDb, layer: &str, idx: usize, include_abutted: bool) -> Result<()>;
        fn cutenclosurerule_set_except_extra_cut(db: &OdbDb, layer: &str, idx: usize, except_extra_cut: bool) -> Result<()>;
        fn cutenclosurerule_set_prl(db: &OdbDb, layer: &str, idx: usize, prl: bool) -> Result<()>;
        fn cutenclosurerule_set_no_shared_edge(db: &OdbDb, layer: &str, idx: usize, no_shared_edge: bool) -> Result<()>;
        fn cutenclosurerule_set_length_valid(db: &OdbDb, layer: &str, idx: usize, length_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_extra_cut_valid(db: &OdbDb, layer: &str, idx: usize, extra_cut_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_extra_only(db: &OdbDb, layer: &str, idx: usize, extra_only: bool) -> Result<()>;
        fn cutenclosurerule_set_redundant_cut_valid(db: &OdbDb, layer: &str, idx: usize, redundant_cut_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_parallel_valid(db: &OdbDb, layer: &str, idx: usize, parallel_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_second_parallel_valid(db: &OdbDb, layer: &str, idx: usize, second_parallel_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_second_par_within_valid(db: &OdbDb, layer: &str, idx: usize, second_par_within_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_below_enclosure_valid(db: &OdbDb, layer: &str, idx: usize, below_enclosure_valid: bool) -> Result<()>;
        fn cutenclosurerule_set_concave_corners_valid(db: &OdbDb, layer: &str, idx: usize, concave_corners_valid: bool) -> Result<()>;
        fn cutspacingrule_set_cut_spacing(db: &OdbDb, layer: &str, idx: usize, cut_spacing: i32) -> Result<()>;
        fn cutspacingrule_set_second_layer(db: &OdbDb, layer: &str, idx: usize, second_layer: &str) -> Result<()>;
        fn cutspacingrule_set_orthogonal_spacing(db: &OdbDb, layer: &str, idx: usize, orthogonal_spacing: i32) -> Result<()>;
        fn cutspacingrule_set_width(db: &OdbDb, layer: &str, idx: usize, width: i32) -> Result<()>;
        fn cutspacingrule_set_enclosure(db: &OdbDb, layer: &str, idx: usize, enclosure: i32) -> Result<()>;
        fn cutspacingrule_set_edge_length(db: &OdbDb, layer: &str, idx: usize, edge_length: i32) -> Result<()>;
        fn cutspacingrule_set_par_within(db: &OdbDb, layer: &str, idx: usize, par_within: i32) -> Result<()>;
        fn cutspacingrule_set_par_enclosure(db: &OdbDb, layer: &str, idx: usize, par_enclosure: i32) -> Result<()>;
        fn cutspacingrule_set_edge_enclosure(db: &OdbDb, layer: &str, idx: usize, edge_enclosure: i32) -> Result<()>;
        fn cutspacingrule_set_adj_enclosure(db: &OdbDb, layer: &str, idx: usize, adj_enclosure: i32) -> Result<()>;
        fn cutspacingrule_set_above_enclosure(db: &OdbDb, layer: &str, idx: usize, above_enclosure: i32) -> Result<()>;
        fn cutspacingrule_set_above_width(db: &OdbDb, layer: &str, idx: usize, above_width: i32) -> Result<()>;
        fn cutspacingrule_set_min_length(db: &OdbDb, layer: &str, idx: usize, min_length: i32) -> Result<()>;
        fn cutspacingrule_set_extension(db: &OdbDb, layer: &str, idx: usize, extension: i32) -> Result<()>;
        fn cutspacingrule_set_eol_width(db: &OdbDb, layer: &str, idx: usize, eol_width: i32) -> Result<()>;
        fn cutspacingrule_set_num_cuts(db: &OdbDb, layer: &str, idx: usize, num_cuts: u32) -> Result<()>;
        fn cutspacingrule_set_within(db: &OdbDb, layer: &str, idx: usize, within: i32) -> Result<()>;
        fn cutspacingrule_set_second_within(db: &OdbDb, layer: &str, idx: usize, second_within: i32) -> Result<()>;
        fn cutspacingrule_set_two_cuts(db: &OdbDb, layer: &str, idx: usize, two_cuts: u32) -> Result<()>;
        fn cutspacingrule_set_prl(db: &OdbDb, layer: &str, idx: usize, prl: u32) -> Result<()>;
        fn cutspacingrule_set_par_length(db: &OdbDb, layer: &str, idx: usize, par_length: u32) -> Result<()>;
        fn cutspacingrule_set_cut_area(db: &OdbDb, layer: &str, idx: usize, cut_area: i64) -> Result<()>;
        fn cutspacingrule_set_center_to_center(db: &OdbDb, layer: &str, idx: usize, center_to_center: bool) -> Result<()>;
        fn cutspacingrule_set_same_net(db: &OdbDb, layer: &str, idx: usize, same_net: bool) -> Result<()>;
        fn cutspacingrule_set_same_metal(db: &OdbDb, layer: &str, idx: usize, same_metal: bool) -> Result<()>;
        fn cutspacingrule_set_same_via(db: &OdbDb, layer: &str, idx: usize, same_via: bool) -> Result<()>;
        fn cutspacingrule_set_stack(db: &OdbDb, layer: &str, idx: usize, stack: bool) -> Result<()>;
        fn cutspacingrule_set_orthogonal_spacing_valid(db: &OdbDb, layer: &str, idx: usize, orthogonal_spacing_valid: bool) -> Result<()>;
        fn cutspacingrule_set_above_width_enclosure_valid(db: &OdbDb, layer: &str, idx: usize, above_width_enclosure_valid: bool) -> Result<()>;
        fn cutspacingrule_set_short_edge_only(db: &OdbDb, layer: &str, idx: usize, short_edge_only: bool) -> Result<()>;
        fn cutspacingrule_set_concave_corner_width(db: &OdbDb, layer: &str, idx: usize, concave_corner_width: bool) -> Result<()>;
        fn cutspacingrule_set_concave_corner_parallel(db: &OdbDb, layer: &str, idx: usize, concave_corner_parallel: bool) -> Result<()>;
        fn cutspacingrule_set_concave_corner_edge_length(db: &OdbDb, layer: &str, idx: usize, concave_corner_edge_length: bool) -> Result<()>;
        fn cutspacingrule_set_concave_corner(db: &OdbDb, layer: &str, idx: usize, concave_corner: bool) -> Result<()>;
        fn cutspacingrule_set_extension_valid(db: &OdbDb, layer: &str, idx: usize, extension_valid: bool) -> Result<()>;
        fn cutspacingrule_set_non_eol_convex_corner(db: &OdbDb, layer: &str, idx: usize, non_eol_convex_corner: bool) -> Result<()>;
        fn cutspacingrule_set_eol_width_valid(db: &OdbDb, layer: &str, idx: usize, eol_width_valid: bool) -> Result<()>;
        fn cutspacingrule_set_min_length_valid(db: &OdbDb, layer: &str, idx: usize, min_length_valid: bool) -> Result<()>;
        fn cutspacingrule_set_above_width_valid(db: &OdbDb, layer: &str, idx: usize, above_width_valid: bool) -> Result<()>;
        fn cutspacingrule_set_mask_overlap(db: &OdbDb, layer: &str, idx: usize, mask_overlap: bool) -> Result<()>;
        fn cutspacingrule_set_wrong_direction(db: &OdbDb, layer: &str, idx: usize, wrong_direction: bool) -> Result<()>;
        fn cutspacingrule_set_adjacent_cuts(db: &OdbDb, layer: &str, idx: usize, adjacent_cuts: u32) -> Result<()>;
        fn cutspacingrule_set_exact_aligned(db: &OdbDb, layer: &str, idx: usize, exact_aligned: bool) -> Result<()>;
        fn cutspacingrule_set_cut_class_to_all(db: &OdbDb, layer: &str, idx: usize, cut_class_to_all: bool) -> Result<()>;
        fn cutspacingrule_set_no_prl(db: &OdbDb, layer: &str, idx: usize, no_prl: bool) -> Result<()>;
        fn cutspacingrule_set_same_mask(db: &OdbDb, layer: &str, idx: usize, same_mask: bool) -> Result<()>;
        fn cutspacingrule_set_except_same_pgnet(db: &OdbDb, layer: &str, idx: usize, except_same_pgnet: bool) -> Result<()>;
        fn cutspacingrule_set_side_parallel_overlap(db: &OdbDb, layer: &str, idx: usize, side_parallel_overlap: bool) -> Result<()>;
        fn cutspacingrule_set_except_same_net(db: &OdbDb, layer: &str, idx: usize, except_same_net: bool) -> Result<()>;
        fn cutspacingrule_set_except_same_metal(db: &OdbDb, layer: &str, idx: usize, except_same_metal: bool) -> Result<()>;
        fn cutspacingrule_set_except_same_metal_overlap(db: &OdbDb, layer: &str, idx: usize, except_same_metal_overlap: bool) -> Result<()>;
        fn cutspacingrule_set_except_same_via(db: &OdbDb, layer: &str, idx: usize, except_same_via: bool) -> Result<()>;
        fn cutspacingrule_set_above(db: &OdbDb, layer: &str, idx: usize, above: bool) -> Result<()>;
        fn cutspacingrule_set_except_two_edges(db: &OdbDb, layer: &str, idx: usize, except_two_edges: bool) -> Result<()>;
        fn cutspacingrule_set_two_cuts_valid(db: &OdbDb, layer: &str, idx: usize, two_cuts_valid: bool) -> Result<()>;
        fn cutspacingrule_set_same_cut(db: &OdbDb, layer: &str, idx: usize, same_cut: bool) -> Result<()>;
        fn cutspacingrule_set_long_edge_only(db: &OdbDb, layer: &str, idx: usize, long_edge_only: bool) -> Result<()>;
        fn cutspacingrule_set_prl_valid(db: &OdbDb, layer: &str, idx: usize, prl_valid: bool) -> Result<()>;
        fn cutspacingrule_set_below(db: &OdbDb, layer: &str, idx: usize, below: bool) -> Result<()>;
        fn cutspacingrule_set_par_within_enclosure_valid(db: &OdbDb, layer: &str, idx: usize, par_within_enclosure_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_second_layer(db: &OdbDb, layer: &str, idx: usize, second_layer: &str) -> Result<()>;
        fn cutspacingtablerule_set_prl(db: &OdbDb, layer: &str, idx: usize, prl: i32) -> Result<()>;
        fn cutspacingtablerule_set_extension(db: &OdbDb, layer: &str, idx: usize, extension: i32) -> Result<()>;
        fn cutspacingtablerule_set_default_valid(db: &OdbDb, layer: &str, idx: usize, default_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_same_mask(db: &OdbDb, layer: &str, idx: usize, same_mask: bool) -> Result<()>;
        fn cutspacingtablerule_set_same_net(db: &OdbDb, layer: &str, idx: usize, same_net: bool) -> Result<()>;
        fn cutspacingtablerule_set_same_metal(db: &OdbDb, layer: &str, idx: usize, same_metal: bool) -> Result<()>;
        fn cutspacingtablerule_set_same_via(db: &OdbDb, layer: &str, idx: usize, same_via: bool) -> Result<()>;
        fn cutspacingtablerule_set_layer_valid(db: &OdbDb, layer: &str, idx: usize, layer_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_no_stack(db: &OdbDb, layer: &str, idx: usize, no_stack: bool) -> Result<()>;
        fn cutspacingtablerule_set_non_zero_enclosure(db: &OdbDb, layer: &str, idx: usize, non_zero_enclosure: bool) -> Result<()>;
        fn cutspacingtablerule_set_prl_for_aligned_cut(db: &OdbDb, layer: &str, idx: usize, prl_for_aligned_cut: bool) -> Result<()>;
        fn cutspacingtablerule_set_center_to_center_valid(db: &OdbDb, layer: &str, idx: usize, center_to_center_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_center_and_edge_valid(db: &OdbDb, layer: &str, idx: usize, center_and_edge_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_no_prl(db: &OdbDb, layer: &str, idx: usize, no_prl: bool) -> Result<()>;
        fn cutspacingtablerule_set_prl_valid(db: &OdbDb, layer: &str, idx: usize, prl_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_max_x_y(db: &OdbDb, layer: &str, idx: usize, max_x_y: bool) -> Result<()>;
        fn cutspacingtablerule_set_end_extension_valid(db: &OdbDb, layer: &str, idx: usize, end_extension_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_side_extension_valid(db: &OdbDb, layer: &str, idx: usize, side_extension_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_exact_aligned_spacing_valid(db: &OdbDb, layer: &str, idx: usize, exact_aligned_spacing_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_horizontal(db: &OdbDb, layer: &str, idx: usize, horizontal: bool) -> Result<()>;
        fn cutspacingtablerule_set_prl_horizontal(db: &OdbDb, layer: &str, idx: usize, prl_horizontal: bool) -> Result<()>;
        fn cutspacingtablerule_set_vertical(db: &OdbDb, layer: &str, idx: usize, vertical: bool) -> Result<()>;
        fn cutspacingtablerule_set_prl_vertical(db: &OdbDb, layer: &str, idx: usize, prl_vertical: bool) -> Result<()>;
        fn cutspacingtablerule_set_non_opposite_enclosure_spacing_valid(db: &OdbDb, layer: &str, idx: usize, non_opposite_enclosure_spacing_valid: bool) -> Result<()>;
        fn cutspacingtablerule_set_opposite_enclosure_resize_spacing_valid(db: &OdbDb, layer: &str, idx: usize, opposite_enclosure_resize_spacing_valid: bool) -> Result<()>;
        fn eolkeepoutrule_set_eol_width(db: &OdbDb, layer: &str, idx: usize, eol_width: i32) -> Result<()>;
        fn eolkeepoutrule_set_backward_ext(db: &OdbDb, layer: &str, idx: usize, backward_ext: i32) -> Result<()>;
        fn eolkeepoutrule_set_forward_ext(db: &OdbDb, layer: &str, idx: usize, forward_ext: i32) -> Result<()>;
        fn eolkeepoutrule_set_side_ext(db: &OdbDb, layer: &str, idx: usize, side_ext: i32) -> Result<()>;
        fn eolkeepoutrule_set_within_low(db: &OdbDb, layer: &str, idx: usize, within_low: i32) -> Result<()>;
        fn eolkeepoutrule_set_within_high(db: &OdbDb, layer: &str, idx: usize, within_high: i32) -> Result<()>;
        fn eolkeepoutrule_set_class_name(db: &OdbDb, layer: &str, idx: usize, class_name: &str) -> Result<()>;
        fn eolkeepoutrule_set_class_valid(db: &OdbDb, layer: &str, idx: usize, class_valid: bool) -> Result<()>;
        fn eolkeepoutrule_set_corner_only(db: &OdbDb, layer: &str, idx: usize, corner_only: bool) -> Result<()>;
        fn eolkeepoutrule_set_except_within(db: &OdbDb, layer: &str, idx: usize, except_within: bool) -> Result<()>;
        fn spacingeolrule_set_eol_space(db: &OdbDb, layer: &str, idx: usize, eol_space: i32) -> Result<()>;
        fn spacingeolrule_set_eol_width(db: &OdbDb, layer: &str, idx: usize, eol_width: i32) -> Result<()>;
        fn spacingeolrule_set_wrong_dir_space(db: &OdbDb, layer: &str, idx: usize, wrong_dir_space: i32) -> Result<()>;
        fn spacingeolrule_set_opposite_width(db: &OdbDb, layer: &str, idx: usize, opposite_width: i32) -> Result<()>;
        fn spacingeolrule_set_eol_within(db: &OdbDb, layer: &str, idx: usize, eol_within: i32) -> Result<()>;
        fn spacingeolrule_set_wrong_dir_within(db: &OdbDb, layer: &str, idx: usize, wrong_dir_within: i32) -> Result<()>;
        fn spacingeolrule_set_exact_width(db: &OdbDb, layer: &str, idx: usize, exact_width: i32) -> Result<()>;
        fn spacingeolrule_set_other_width(db: &OdbDb, layer: &str, idx: usize, other_width: i32) -> Result<()>;
        fn spacingeolrule_set_fill_triangle(db: &OdbDb, layer: &str, idx: usize, fill_triangle: i32) -> Result<()>;
        fn spacingeolrule_set_cut_class(db: &OdbDb, layer: &str, idx: usize, cut_class: i32) -> Result<()>;
        fn spacingeolrule_set_with_cut_space(db: &OdbDb, layer: &str, idx: usize, with_cut_space: i32) -> Result<()>;
        fn spacingeolrule_set_enclosure_end_width(db: &OdbDb, layer: &str, idx: usize, enclosure_end_width: i32) -> Result<()>;
        fn spacingeolrule_set_enclosure_end_within(db: &OdbDb, layer: &str, idx: usize, enclosure_end_within: i32) -> Result<()>;
        fn spacingeolrule_set_end_prl_space(db: &OdbDb, layer: &str, idx: usize, end_prl_space: i32) -> Result<()>;
        fn spacingeolrule_set_end_prl(db: &OdbDb, layer: &str, idx: usize, end_prl: i32) -> Result<()>;
        fn spacingeolrule_set_end_to_end_space(db: &OdbDb, layer: &str, idx: usize, end_to_end_space: i32) -> Result<()>;
        fn spacingeolrule_set_one_cut_space(db: &OdbDb, layer: &str, idx: usize, one_cut_space: i32) -> Result<()>;
        fn spacingeolrule_set_two_cut_space(db: &OdbDb, layer: &str, idx: usize, two_cut_space: i32) -> Result<()>;
        fn spacingeolrule_set_extension(db: &OdbDb, layer: &str, idx: usize, extension: i32) -> Result<()>;
        fn spacingeolrule_set_wrong_dir_extension(db: &OdbDb, layer: &str, idx: usize, wrong_dir_extension: i32) -> Result<()>;
        fn spacingeolrule_set_other_end_width(db: &OdbDb, layer: &str, idx: usize, other_end_width: i32) -> Result<()>;
        fn spacingeolrule_set_max_length(db: &OdbDb, layer: &str, idx: usize, max_length: i32) -> Result<()>;
        fn spacingeolrule_set_min_length(db: &OdbDb, layer: &str, idx: usize, min_length: i32) -> Result<()>;
        fn spacingeolrule_set_par_space(db: &OdbDb, layer: &str, idx: usize, par_space: i32) -> Result<()>;
        fn spacingeolrule_set_par_within(db: &OdbDb, layer: &str, idx: usize, par_within: i32) -> Result<()>;
        fn spacingeolrule_set_par_prl(db: &OdbDb, layer: &str, idx: usize, par_prl: i32) -> Result<()>;
        fn spacingeolrule_set_par_min_length(db: &OdbDb, layer: &str, idx: usize, par_min_length: i32) -> Result<()>;
        fn spacingeolrule_set_enclose_dist(db: &OdbDb, layer: &str, idx: usize, enclose_dist: i32) -> Result<()>;
        fn spacingeolrule_set_cut_to_metal_space(db: &OdbDb, layer: &str, idx: usize, cut_to_metal_space: i32) -> Result<()>;
        fn spacingeolrule_set_min_adj_length(db: &OdbDb, layer: &str, idx: usize, min_adj_length: i32) -> Result<()>;
        fn spacingeolrule_set_min_adj_length1(db: &OdbDb, layer: &str, idx: usize, min_adj_length1: i32) -> Result<()>;
        fn spacingeolrule_set_min_adj_length2(db: &OdbDb, layer: &str, idx: usize, min_adj_length2: i32) -> Result<()>;
        fn spacingeolrule_set_notch_length(db: &OdbDb, layer: &str, idx: usize, notch_length: i32) -> Result<()>;
        fn spacingeolrule_set_exact_width_valid(db: &OdbDb, layer: &str, idx: usize, exact_width_valid: bool) -> Result<()>;
        fn spacingeolrule_set_wrong_dir_spacing_valid(db: &OdbDb, layer: &str, idx: usize, wrong_dir_spacing_valid: bool) -> Result<()>;
        fn spacingeolrule_set_opposite_width_valid(db: &OdbDb, layer: &str, idx: usize, opposite_width_valid: bool) -> Result<()>;
        fn spacingeolrule_set_within_valid(db: &OdbDb, layer: &str, idx: usize, within_valid: bool) -> Result<()>;
        fn spacingeolrule_set_wrong_dir_within_valid(db: &OdbDb, layer: &str, idx: usize, wrong_dir_within_valid: bool) -> Result<()>;
        fn spacingeolrule_set_same_mask_valid(db: &OdbDb, layer: &str, idx: usize, same_mask_valid: bool) -> Result<()>;
        fn spacingeolrule_set_except_exact_width_valid(db: &OdbDb, layer: &str, idx: usize, except_exact_width_valid: bool) -> Result<()>;
        fn spacingeolrule_set_fill_concave_corner_valid(db: &OdbDb, layer: &str, idx: usize, fill_concave_corner_valid: bool) -> Result<()>;
        fn spacingeolrule_set_withcut_valid(db: &OdbDb, layer: &str, idx: usize, withcut_valid: bool) -> Result<()>;
        fn spacingeolrule_set_cut_class_valid(db: &OdbDb, layer: &str, idx: usize, cut_class_valid: bool) -> Result<()>;
        fn spacingeolrule_set_with_cut_above_valid(db: &OdbDb, layer: &str, idx: usize, with_cut_above_valid: bool) -> Result<()>;
        fn spacingeolrule_set_enclosure_end_valid(db: &OdbDb, layer: &str, idx: usize, enclosure_end_valid: bool) -> Result<()>;
        fn spacingeolrule_set_enclosure_end_within_valid(db: &OdbDb, layer: &str, idx: usize, enclosure_end_within_valid: bool) -> Result<()>;
        fn spacingeolrule_set_end_prl_spacing_valid(db: &OdbDb, layer: &str, idx: usize, end_prl_spacing_valid: bool) -> Result<()>;
        fn spacingeolrule_set_prl_valid(db: &OdbDb, layer: &str, idx: usize, prl_valid: bool) -> Result<()>;
        fn spacingeolrule_set_end_to_end_valid(db: &OdbDb, layer: &str, idx: usize, end_to_end_valid: bool) -> Result<()>;
        fn spacingeolrule_set_cut_spaces_valid(db: &OdbDb, layer: &str, idx: usize, cut_spaces_valid: bool) -> Result<()>;
        fn spacingeolrule_set_extension_valid(db: &OdbDb, layer: &str, idx: usize, extension_valid: bool) -> Result<()>;
        fn spacingeolrule_set_wrong_dir_extension_valid(db: &OdbDb, layer: &str, idx: usize, wrong_dir_extension_valid: bool) -> Result<()>;
        fn spacingeolrule_set_other_end_width_valid(db: &OdbDb, layer: &str, idx: usize, other_end_width_valid: bool) -> Result<()>;
        fn spacingeolrule_set_max_length_valid(db: &OdbDb, layer: &str, idx: usize, max_length_valid: bool) -> Result<()>;
        fn spacingeolrule_set_min_length_valid(db: &OdbDb, layer: &str, idx: usize, min_length_valid: bool) -> Result<()>;
        fn spacingeolrule_set_two_sides_valid(db: &OdbDb, layer: &str, idx: usize, two_sides_valid: bool) -> Result<()>;
        fn spacingeolrule_set_equal_rect_width_valid(db: &OdbDb, layer: &str, idx: usize, equal_rect_width_valid: bool) -> Result<()>;
        fn spacingeolrule_set_parallel_edge_valid(db: &OdbDb, layer: &str, idx: usize, parallel_edge_valid: bool) -> Result<()>;
        fn spacingeolrule_set_subtract_eol_width_valid(db: &OdbDb, layer: &str, idx: usize, subtract_eol_width_valid: bool) -> Result<()>;
        fn spacingeolrule_set_par_prl_valid(db: &OdbDb, layer: &str, idx: usize, par_prl_valid: bool) -> Result<()>;
        fn spacingeolrule_set_par_min_length_valid(db: &OdbDb, layer: &str, idx: usize, par_min_length_valid: bool) -> Result<()>;
        fn spacingeolrule_set_two_edges_valid(db: &OdbDb, layer: &str, idx: usize, two_edges_valid: bool) -> Result<()>;
        fn spacingeolrule_set_same_metal_valid(db: &OdbDb, layer: &str, idx: usize, same_metal_valid: bool) -> Result<()>;
        fn spacingeolrule_set_non_eol_corner_only_valid(db: &OdbDb, layer: &str, idx: usize, non_eol_corner_only_valid: bool) -> Result<()>;
        fn spacingeolrule_set_parallel_same_mask_valid(db: &OdbDb, layer: &str, idx: usize, parallel_same_mask_valid: bool) -> Result<()>;
        fn spacingeolrule_set_enclose_cut_valid(db: &OdbDb, layer: &str, idx: usize, enclose_cut_valid: bool) -> Result<()>;
        fn spacingeolrule_set_below_valid(db: &OdbDb, layer: &str, idx: usize, below_valid: bool) -> Result<()>;
        fn spacingeolrule_set_above_valid(db: &OdbDb, layer: &str, idx: usize, above_valid: bool) -> Result<()>;
        fn spacingeolrule_set_cut_spacing_valid(db: &OdbDb, layer: &str, idx: usize, cut_spacing_valid: bool) -> Result<()>;
        fn spacingeolrule_set_all_cuts_valid(db: &OdbDb, layer: &str, idx: usize, all_cuts_valid: bool) -> Result<()>;
        fn spacingeolrule_set_to_concave_corner_valid(db: &OdbDb, layer: &str, idx: usize, to_concave_corner_valid: bool) -> Result<()>;
        fn spacingeolrule_set_min_adjacent_length_valid(db: &OdbDb, layer: &str, idx: usize, min_adjacent_length_valid: bool) -> Result<()>;
        fn spacingeolrule_set_two_min_adj_length_valid(db: &OdbDb, layer: &str, idx: usize, two_min_adj_length_valid: bool) -> Result<()>;
        fn spacingeolrule_set_to_notch_length_valid(db: &OdbDb, layer: &str, idx: usize, to_notch_length_valid: bool) -> Result<()>;
        fn cornerspacingrule_set_within(db: &OdbDb, layer: &str, idx: usize, within: i32) -> Result<()>;
        fn cornerspacingrule_set_eol_width(db: &OdbDb, layer: &str, idx: usize, eol_width: i32) -> Result<()>;
        fn cornerspacingrule_set_jog_length(db: &OdbDb, layer: &str, idx: usize, jog_length: i32) -> Result<()>;
        fn cornerspacingrule_set_edge_length(db: &OdbDb, layer: &str, idx: usize, edge_length: i32) -> Result<()>;
        fn cornerspacingrule_set_min_length(db: &OdbDb, layer: &str, idx: usize, min_length: i32) -> Result<()>;
        fn cornerspacingrule_set_except_notch_length(db: &OdbDb, layer: &str, idx: usize, except_notch_length: i32) -> Result<()>;
        fn cornerspacingrule_set_same_mask(db: &OdbDb, layer: &str, idx: usize, same_mask: bool) -> Result<()>;
        fn cornerspacingrule_set_corner_only(db: &OdbDb, layer: &str, idx: usize, corner_only: bool) -> Result<()>;
        fn cornerspacingrule_set_except_eol(db: &OdbDb, layer: &str, idx: usize, except_eol: bool) -> Result<()>;
        fn cornerspacingrule_set_except_jog_length(db: &OdbDb, layer: &str, idx: usize, except_jog_length: bool) -> Result<()>;
        fn cornerspacingrule_set_edge_length_valid(db: &OdbDb, layer: &str, idx: usize, edge_length_valid: bool) -> Result<()>;
        fn cornerspacingrule_set_include_shape(db: &OdbDb, layer: &str, idx: usize, include_shape: bool) -> Result<()>;
        fn cornerspacingrule_set_min_length_valid(db: &OdbDb, layer: &str, idx: usize, min_length_valid: bool) -> Result<()>;
        fn cornerspacingrule_set_except_notch(db: &OdbDb, layer: &str, idx: usize, except_notch: bool) -> Result<()>;
        fn cornerspacingrule_set_except_notch_length_valid(db: &OdbDb, layer: &str, idx: usize, except_notch_length_valid: bool) -> Result<()>;
        fn cornerspacingrule_set_except_same_net(db: &OdbDb, layer: &str, idx: usize, except_same_net: bool) -> Result<()>;
        fn cornerspacingrule_set_except_same_metal(db: &OdbDb, layer: &str, idx: usize, except_same_metal: bool) -> Result<()>;
        fn cornerspacingrule_set_corner_to_corner(db: &OdbDb, layer: &str, idx: usize, corner_to_corner: bool) -> Result<()>;
        fn minsteprule_set_min_step_length(db: &OdbDb, layer: &str, idx: usize, min_step_length: i32) -> Result<()>;
        fn minsteprule_set_max_edges(db: &OdbDb, layer: &str, idx: usize, max_edges: u32) -> Result<()>;
        fn minsteprule_set_min_adj_length1(db: &OdbDb, layer: &str, idx: usize, min_adj_length1: i32) -> Result<()>;
        fn minsteprule_set_min_adj_length2(db: &OdbDb, layer: &str, idx: usize, min_adj_length2: i32) -> Result<()>;
        fn minsteprule_set_eol_width(db: &OdbDb, layer: &str, idx: usize, eol_width: i32) -> Result<()>;
        fn minsteprule_set_min_between_length(db: &OdbDb, layer: &str, idx: usize, min_between_length: i32) -> Result<()>;
        fn minsteprule_set_max_edges_valid(db: &OdbDb, layer: &str, idx: usize, max_edges_valid: bool) -> Result<()>;
        fn minsteprule_set_min_adj_length1_valid(db: &OdbDb, layer: &str, idx: usize, min_adj_length1_valid: bool) -> Result<()>;
        fn minsteprule_set_no_between_eol(db: &OdbDb, layer: &str, idx: usize, no_between_eol: bool) -> Result<()>;
        fn minsteprule_set_min_adj_length2_valid(db: &OdbDb, layer: &str, idx: usize, min_adj_length2_valid: bool) -> Result<()>;
        fn minsteprule_set_convex_corner(db: &OdbDb, layer: &str, idx: usize, convex_corner: bool) -> Result<()>;
        fn minsteprule_set_min_between_length_valid(db: &OdbDb, layer: &str, idx: usize, min_between_length_valid: bool) -> Result<()>;
        fn minsteprule_set_except_same_corners(db: &OdbDb, layer: &str, idx: usize, except_same_corners: bool) -> Result<()>;
        fn minsteprule_set_concave_corner(db: &OdbDb, layer: &str, idx: usize, concave_corner: bool) -> Result<()>;
        fn minsteprule_set_except_rectangle(db: &OdbDb, layer: &str, idx: usize, except_rectangle: bool) -> Result<()>;
        fn minsteprule_set_no_adjacent_eol(db: &OdbDb, layer: &str, idx: usize, no_adjacent_eol: bool) -> Result<()>;
        fn mincutrule_set_num_cuts(db: &OdbDb, layer: &str, idx: usize, num_cuts: i32) -> Result<()>;
        fn mincutrule_set_width(db: &OdbDb, layer: &str, idx: usize, width: i32) -> Result<()>;
        fn mincutrule_set_within_cut_dist(db: &OdbDb, layer: &str, idx: usize, within_cut_dist: i32) -> Result<()>;
        fn mincutrule_set_length(db: &OdbDb, layer: &str, idx: usize, length: i32) -> Result<()>;
        fn mincutrule_set_length_within_dist(db: &OdbDb, layer: &str, idx: usize, length_within_dist: i32) -> Result<()>;
        fn mincutrule_set_area(db: &OdbDb, layer: &str, idx: usize, area: i64) -> Result<()>;
        fn mincutrule_set_area_within_dist(db: &OdbDb, layer: &str, idx: usize, area_within_dist: i32) -> Result<()>;
        fn mincutrule_set_per_cut_class(db: &OdbDb, layer: &str, idx: usize, per_cut_class: bool) -> Result<()>;
        fn mincutrule_set_within_cut_dist_valid(db: &OdbDb, layer: &str, idx: usize, within_cut_dist_valid: bool) -> Result<()>;
        fn mincutrule_set_from_above(db: &OdbDb, layer: &str, idx: usize, from_above: bool) -> Result<()>;
        fn mincutrule_set_from_below(db: &OdbDb, layer: &str, idx: usize, from_below: bool) -> Result<()>;
        fn mincutrule_set_length_valid(db: &OdbDb, layer: &str, idx: usize, length_valid: bool) -> Result<()>;
        fn mincutrule_set_area_valid(db: &OdbDb, layer: &str, idx: usize, area_valid: bool) -> Result<()>;
        fn mincutrule_set_area_within_dist_valid(db: &OdbDb, layer: &str, idx: usize, area_within_dist_valid: bool) -> Result<()>;
        fn mincutrule_set_same_metal_overlap(db: &OdbDb, layer: &str, idx: usize, same_metal_overlap: bool) -> Result<()>;
        fn mincutrule_set_fully_enclosed(db: &OdbDb, layer: &str, idx: usize, fully_enclosed: bool) -> Result<()>;
        fn mincutrule_set_cuts_per_cut_class(db: &OdbDb, layer: &str, idx: usize, cut_class: &str, num_cuts: i32) -> Result<()>;
        fn maxspacingrule_set_cut_class(db: &OdbDb, layer: &str, idx: usize, cut_class: &str) -> Result<()>;
        fn maxspacingrule_set_max_spacing(db: &OdbDb, layer: &str, idx: usize, max_spacing: i32) -> Result<()>;
        fn twowiresforbiddenrule_set_min_spacing(db: &OdbDb, layer: &str, idx: usize, min_spacing: i32) -> Result<()>;
        fn twowiresforbiddenrule_set_max_spacing(db: &OdbDb, layer: &str, idx: usize, max_spacing: i32) -> Result<()>;
        fn twowiresforbiddenrule_set_min_span_length(db: &OdbDb, layer: &str, idx: usize, min_span_length: i32) -> Result<()>;
        fn twowiresforbiddenrule_set_max_span_length(db: &OdbDb, layer: &str, idx: usize, max_span_length: i32) -> Result<()>;
        fn twowiresforbiddenrule_set_prl(db: &OdbDb, layer: &str, idx: usize, prl: i32) -> Result<()>;
        fn twowiresforbiddenrule_set_min_exact_span_length(db: &OdbDb, layer: &str, idx: usize, min_exact_span_length: bool) -> Result<()>;
        fn twowiresforbiddenrule_set_max_exact_span_length(db: &OdbDb, layer: &str, idx: usize, max_exact_span_length: bool) -> Result<()>;
        fn widthtablerule_set_wrong_direction(db: &OdbDb, layer: &str, idx: usize, wrong_direction: bool) -> Result<()>;
        fn widthtablerule_set_orthogonal(db: &OdbDb, layer: &str, idx: usize, orthogonal: bool) -> Result<()>;
        fn wrongdirspacingrule_set_wrongdir_space(db: &OdbDb, layer: &str, idx: usize, wrongdir_space: i32) -> Result<()>;
        fn wrongdirspacingrule_set_noneol_width(db: &OdbDb, layer: &str, idx: usize, noneol_width: i32) -> Result<()>;
        fn wrongdirspacingrule_set_length(db: &OdbDb, layer: &str, idx: usize, length: i32) -> Result<()>;
        fn wrongdirspacingrule_set_prl_length(db: &OdbDb, layer: &str, idx: usize, prl_length: i32) -> Result<()>;
        fn wrongdirspacingrule_set_noneol_valid(db: &OdbDb, layer: &str, idx: usize, noneol_valid: bool) -> Result<()>;
        fn wrongdirspacingrule_set_length_valid(db: &OdbDb, layer: &str, idx: usize, length_valid: bool) -> Result<()>;
        fn layerantenna_set_gate_plus_diff_factor(db: &OdbDb, layer: &str, factor: f64) -> Result<()>;
        fn layerantenna_set_area_minus_diff_factor(db: &OdbDb, layer: &str, factor: f64) -> Result<()>;
        fn layerantenna_set_area_factor(db: &OdbDb, layer: &str, factor: f64, diffuse: bool) -> Result<()>;
        fn layerantenna_set_side_area_factor(db: &OdbDb, layer: &str, factor: f64, diffuse: bool) -> Result<()>;
        fn layerantenna_set_antenna_cum_routing_plus_cut(db: &OdbDb, layer: &str, value: bool) -> Result<()>;
        fn layerantenna_set_p_a_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn layerantenna_set_c_a_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn layerantenna_set_p_s_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn layerantenna_set_c_s_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn layerantenna_set_diff_p_a_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn layerantenna_set_diff_c_a_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn layerantenna_set_diff_p_s_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn layerantenna_set_diff_c_s_r(db: &OdbDb, layer: &str, ratio: f64) -> Result<()>;
        fn chip_set_offset(db: &OdbDb, chip: &str, x: i32, y: i32) -> Result<()>;
        fn chip_set_width(db: &OdbDb, chip: &str, width: i32) -> Result<()>;
        fn chip_set_height(db: &OdbDb, chip: &str, height: i32) -> Result<()>;
        fn chip_set_thickness(db: &OdbDb, chip: &str, thickness: i32) -> Result<()>;
        fn chip_set_shrink(db: &OdbDb, chip: &str, shrink: f32) -> Result<()>;
        fn chip_set_seal_ring_east(db: &OdbDb, chip: &str, seal_ring_east: i32) -> Result<()>;
        fn chip_set_seal_ring_west(db: &OdbDb, chip: &str, seal_ring_west: i32) -> Result<()>;
        fn chip_set_seal_ring_north(db: &OdbDb, chip: &str, seal_ring_north: i32) -> Result<()>;
        fn chip_set_seal_ring_south(db: &OdbDb, chip: &str, seal_ring_south: i32) -> Result<()>;
        fn chip_set_scribe_line_east(db: &OdbDb, chip: &str, scribe_line_east: i32) -> Result<()>;
        fn chip_set_scribe_line_west(db: &OdbDb, chip: &str, scribe_line_west: i32) -> Result<()>;
        fn chip_set_scribe_line_north(db: &OdbDb, chip: &str, scribe_line_north: i32) -> Result<()>;
        fn chip_set_scribe_line_south(db: &OdbDb, chip: &str, scribe_line_south: i32) -> Result<()>;
        fn chip_set_tsv(db: &OdbDb, chip: &str, tsv: bool) -> Result<()>;
        fn chipinst_set_orient(db: &OdbDb, chip: &str, inst: &str, orient: &str) -> Result<()>;
        fn chipinst_set_loc(db: &OdbDb, chip: &str, inst: &str, x: i32, y: i32, z: i32) -> Result<()>;
        fn chipbump_set_net(db: &OdbDb, chip: &str, region: &str, idx: usize, net: &str) -> Result<()>;
        fn chipbump_set_b_term(db: &OdbDb, chip: &str, region: &str, idx: usize, bterm: &str) -> Result<()>;
        fn chipconn_set_thickness(db: &OdbDb, chip: &str, conn: &str, thickness: i32) -> Result<()>;
    }
}

pub use ffi_gen_write::{
    block_clear,
    block_clear_global_connect,
    block_clear_user_inst_flags,
    block_set_corner_count,
    block_set_corner_name_list,
    block_set_driving_itermsfor_nets,
    block_set_max_layer_for_clock,
    block_set_max_routing_layer,
    block_set_min_layer_for_clock,
    block_set_min_routing_layer,
    blockage_set_is_system_reserved,
    blockage_set_max_density,
    blockage_set_pushed_down,
    blockage_set_soft,
    box_set_layer_mask,
    box_set_soft,
    bpin_set_effective_width,
    bpin_set_min_spacing,
    bpin_set_placement_status,
    bterm_set_ext_id,
    bterm_set_ground_pin,
    bterm_set_mark,
    bterm_set_mirrored_b_term,
    bterm_set_sig_type,
    bterm_set_special,
    bterm_set_spef_mark,
    bterm_set_supply_pin,
    capnode_set_b_term_flag,
    capnode_set_branch_flag,
    capnode_set_capacitance,
    capnode_set_children_cnt,
    capnode_set_foreign_flag,
    capnode_set_i_term_flag,
    capnode_set_internal_flag,
    capnode_set_name_flag,
    capnode_set_net,
    capnode_set_next,
    capnode_set_node,
    capnode_set_select,
    capnode_set_sort_index,
    ccseg_set_capacitance,
    ccseg_set_mark,
    chip_set_height,
    chip_set_offset,
    chip_set_scribe_line_east,
    chip_set_scribe_line_north,
    chip_set_scribe_line_south,
    chip_set_scribe_line_west,
    chip_set_seal_ring_east,
    chip_set_seal_ring_north,
    chip_set_seal_ring_south,
    chip_set_seal_ring_west,
    chip_set_shrink,
    chip_set_thickness,
    chip_set_tsv,
    chip_set_width,
    chipbump_set_b_term,
    chipbump_set_net,
    chipconn_set_thickness,
    chipinst_set_loc,
    chipinst_set_orient,
    cornerspacingrule_set_corner_only,
    cornerspacingrule_set_corner_to_corner,
    cornerspacingrule_set_edge_length,
    cornerspacingrule_set_edge_length_valid,
    cornerspacingrule_set_eol_width,
    cornerspacingrule_set_except_eol,
    cornerspacingrule_set_except_jog_length,
    cornerspacingrule_set_except_notch,
    cornerspacingrule_set_except_notch_length,
    cornerspacingrule_set_except_notch_length_valid,
    cornerspacingrule_set_except_same_metal,
    cornerspacingrule_set_except_same_net,
    cornerspacingrule_set_include_shape,
    cornerspacingrule_set_jog_length,
    cornerspacingrule_set_min_length,
    cornerspacingrule_set_min_length_valid,
    cornerspacingrule_set_same_mask,
    cornerspacingrule_set_within,
    cutclassrule_set_cuts_valid,
    cutclassrule_set_length,
    cutclassrule_set_length_valid,
    cutclassrule_set_num_cuts,
    cutclassrule_set_width,
    cutenclosurerule_set_above,
    cutenclosurerule_set_backward_extension,
    cutenclosurerule_set_below,
    cutenclosurerule_set_below_enclosure,
    cutenclosurerule_set_below_enclosure_valid,
    cutenclosurerule_set_concave_corners_valid,
    cutenclosurerule_set_cut_class_valid,
    cutenclosurerule_set_cut_within,
    cutenclosurerule_set_end_spacing_valid,
    cutenclosurerule_set_eol_min_length,
    cutenclosurerule_set_eol_min_length_valid,
    cutenclosurerule_set_eol_only,
    cutenclosurerule_set_eol_width,
    cutenclosurerule_set_except_extra_cut,
    cutenclosurerule_set_extension,
    cutenclosurerule_set_extra_cut_valid,
    cutenclosurerule_set_extra_only,
    cutenclosurerule_set_first_overhang,
    cutenclosurerule_set_forward_extension,
    cutenclosurerule_set_include_abutted,
    cutenclosurerule_set_length_valid,
    cutenclosurerule_set_min_length,
    cutenclosurerule_set_min_width,
    cutenclosurerule_set_no_shared_edge,
    cutenclosurerule_set_num_corners,
    cutenclosurerule_set_off_center_line,
    cutenclosurerule_set_par_length,
    cutenclosurerule_set_par_within,
    cutenclosurerule_set_parallel_valid,
    cutenclosurerule_set_prl,
    cutenclosurerule_set_redundant_cut_valid,
    cutenclosurerule_set_second_overhang,
    cutenclosurerule_set_second_par_length,
    cutenclosurerule_set_second_par_within,
    cutenclosurerule_set_second_par_within_valid,
    cutenclosurerule_set_second_parallel_valid,
    cutenclosurerule_set_short_edge_on_eol,
    cutenclosurerule_set_side_spacing_valid,
    cutenclosurerule_set_spacing,
    cutenclosurerule_set_width_valid,
    cutspacingrule_set_above,
    cutspacingrule_set_above_enclosure,
    cutspacingrule_set_above_width,
    cutspacingrule_set_above_width_enclosure_valid,
    cutspacingrule_set_above_width_valid,
    cutspacingrule_set_adj_enclosure,
    cutspacingrule_set_adjacent_cuts,
    cutspacingrule_set_below,
    cutspacingrule_set_center_to_center,
    cutspacingrule_set_concave_corner,
    cutspacingrule_set_concave_corner_edge_length,
    cutspacingrule_set_concave_corner_parallel,
    cutspacingrule_set_concave_corner_width,
    cutspacingrule_set_cut_area,
    cutspacingrule_set_cut_class_to_all,
    cutspacingrule_set_cut_spacing,
    cutspacingrule_set_edge_enclosure,
    cutspacingrule_set_edge_length,
    cutspacingrule_set_enclosure,
    cutspacingrule_set_eol_width,
    cutspacingrule_set_eol_width_valid,
    cutspacingrule_set_exact_aligned,
    cutspacingrule_set_except_same_metal,
    cutspacingrule_set_except_same_metal_overlap,
    cutspacingrule_set_except_same_net,
    cutspacingrule_set_except_same_pgnet,
    cutspacingrule_set_except_same_via,
    cutspacingrule_set_except_two_edges,
    cutspacingrule_set_extension,
    cutspacingrule_set_extension_valid,
    cutspacingrule_set_long_edge_only,
    cutspacingrule_set_mask_overlap,
    cutspacingrule_set_min_length,
    cutspacingrule_set_min_length_valid,
    cutspacingrule_set_no_prl,
    cutspacingrule_set_non_eol_convex_corner,
    cutspacingrule_set_num_cuts,
    cutspacingrule_set_orthogonal_spacing,
    cutspacingrule_set_orthogonal_spacing_valid,
    cutspacingrule_set_par_enclosure,
    cutspacingrule_set_par_length,
    cutspacingrule_set_par_within,
    cutspacingrule_set_par_within_enclosure_valid,
    cutspacingrule_set_prl,
    cutspacingrule_set_prl_valid,
    cutspacingrule_set_same_cut,
    cutspacingrule_set_same_mask,
    cutspacingrule_set_same_metal,
    cutspacingrule_set_same_net,
    cutspacingrule_set_same_via,
    cutspacingrule_set_second_layer,
    cutspacingrule_set_second_within,
    cutspacingrule_set_short_edge_only,
    cutspacingrule_set_side_parallel_overlap,
    cutspacingrule_set_stack,
    cutspacingrule_set_two_cuts,
    cutspacingrule_set_two_cuts_valid,
    cutspacingrule_set_width,
    cutspacingrule_set_within,
    cutspacingrule_set_wrong_direction,
    cutspacingtablerule_set_center_and_edge_valid,
    cutspacingtablerule_set_center_to_center_valid,
    cutspacingtablerule_set_default_valid,
    cutspacingtablerule_set_end_extension_valid,
    cutspacingtablerule_set_exact_aligned_spacing_valid,
    cutspacingtablerule_set_extension,
    cutspacingtablerule_set_horizontal,
    cutspacingtablerule_set_layer_valid,
    cutspacingtablerule_set_max_x_y,
    cutspacingtablerule_set_no_prl,
    cutspacingtablerule_set_no_stack,
    cutspacingtablerule_set_non_opposite_enclosure_spacing_valid,
    cutspacingtablerule_set_non_zero_enclosure,
    cutspacingtablerule_set_opposite_enclosure_resize_spacing_valid,
    cutspacingtablerule_set_prl,
    cutspacingtablerule_set_prl_for_aligned_cut,
    cutspacingtablerule_set_prl_horizontal,
    cutspacingtablerule_set_prl_valid,
    cutspacingtablerule_set_prl_vertical,
    cutspacingtablerule_set_same_mask,
    cutspacingtablerule_set_same_metal,
    cutspacingtablerule_set_same_net,
    cutspacingtablerule_set_same_via,
    cutspacingtablerule_set_second_layer,
    cutspacingtablerule_set_side_extension_valid,
    cutspacingtablerule_set_vertical,
    eolkeepoutrule_set_backward_ext,
    eolkeepoutrule_set_class_name,
    eolkeepoutrule_set_class_valid,
    eolkeepoutrule_set_corner_only,
    eolkeepoutrule_set_eol_width,
    eolkeepoutrule_set_except_within,
    eolkeepoutrule_set_forward_ext,
    eolkeepoutrule_set_side_ext,
    eolkeepoutrule_set_within_high,
    eolkeepoutrule_set_within_low,
    gcell_set_capacity,
    gcell_set_usage,
    guide_set_is_connected_to_term,
    guide_set_is_jumper,
    inst_clear_user_flag1,
    inst_clear_user_flag2,
    inst_clear_user_flag3,
    inst_set_do_not_touch,
    inst_set_eco_create,
    inst_set_eco_destroy,
    inst_set_eco_modify,
    inst_set_halo,
    inst_set_location,
    inst_set_location_orient,
    inst_set_orient,
    inst_set_origin,
    inst_set_pin_access_idx,
    inst_set_placement_status,
    inst_set_source_type,
    inst_set_user_flag1,
    inst_set_user_flag2,
    inst_set_user_flag3,
    inst_set_weight,
    isolation_set_applies_to,
    isolation_set_clamp_value,
    isolation_set_isolation_sense,
    isolation_set_isolation_signal,
    isolation_set_location,
    isolation_set_power_domain,
    iterm_clear_connected,
    iterm_clear_pref_access_points,
    iterm_clear_special,
    iterm_set_clocked,
    iterm_set_connected,
    iterm_set_ext_id,
    iterm_set_mark,
    iterm_set_special,
    iterm_set_spef,
    layer_set_alias,
    layer_set_area,
    layer_set_backside,
    layer_set_capacitance,
    layer_set_edge_capacitance,
    layer_set_first_last_pitch,
    layer_set_layer_adjustment,
    layer_set_max_width,
    layer_set_min_step,
    layer_set_min_step_max_edges,
    layer_set_min_step_max_length,
    layer_set_min_width,
    layer_set_num_masks,
    layer_set_offset,
    layer_set_offset_x_y,
    layer_set_pitch,
    layer_set_pitch_x_y,
    layer_set_protrusion,
    layer_set_rect_only,
    layer_set_rect_only_except_non_core_pins,
    layer_set_resistance,
    layer_set_right_way_on_grid_only,
    layer_set_right_way_on_grid_only_check_mask,
    layer_set_spacing,
    layer_set_thickness,
    layer_set_width,
    layer_set_wire_extension,
    layer_set_wrong_way_min_width,
    layer_set_wrong_way_width,
    layerantenna_set_antenna_cum_routing_plus_cut,
    layerantenna_set_area_factor,
    layerantenna_set_area_minus_diff_factor,
    layerantenna_set_c_a_r,
    layerantenna_set_c_s_r,
    layerantenna_set_diff_c_a_r,
    layerantenna_set_diff_c_s_r,
    layerantenna_set_diff_p_a_r,
    layerantenna_set_diff_p_s_r,
    layerantenna_set_gate_plus_diff_factor,
    layerantenna_set_p_a_r,
    layerantenna_set_p_s_r,
    layerantenna_set_side_area_factor,
    level_shifter_set_applies_to,
    level_shifter_set_applies_to_boundary,
    level_shifter_set_cell_input,
    level_shifter_set_cell_name,
    level_shifter_set_cell_output,
    level_shifter_set_force_shift,
    level_shifter_set_input_supply,
    level_shifter_set_internal_supply,
    level_shifter_set_location,
    level_shifter_set_name_prefix,
    level_shifter_set_name_suffix,
    level_shifter_set_no_shift,
    level_shifter_set_output_supply,
    level_shifter_set_rule,
    level_shifter_set_sink,
    level_shifter_set_source,
    level_shifter_set_threshold,
    level_shifter_set_use_functional_equivalence,
    lib_set_lef_units,
    marker_cat_set_description,
    marker_cat_set_max_markers,
    marker_cat_set_source,
    marker_set_comment,
    marker_set_line_number,
    marker_set_tech_layer,
    marker_set_visible,
    marker_set_visited,
    marker_set_waived,
    master_clear_pin_access,
    master_set_backside_bridge,
    master_set_e_e_q,
    master_set_frozen,
    master_set_height,
    master_set_l_e_q,
    master_set_mark,
    master_set_origin,
    master_set_sequential,
    master_set_site,
    master_set_special_power,
    master_set_symmetry_r90,
    master_set_symmetry_x,
    master_set_symmetry_y,
    master_set_width,
    maxspacingrule_set_cut_class,
    maxspacingrule_set_max_spacing,
    mincutrule_set_area,
    mincutrule_set_area_valid,
    mincutrule_set_area_within_dist,
    mincutrule_set_area_within_dist_valid,
    mincutrule_set_cuts_per_cut_class,
    mincutrule_set_from_above,
    mincutrule_set_from_below,
    mincutrule_set_fully_enclosed,
    mincutrule_set_length,
    mincutrule_set_length_valid,
    mincutrule_set_length_within_dist,
    mincutrule_set_num_cuts,
    mincutrule_set_per_cut_class,
    mincutrule_set_same_metal_overlap,
    mincutrule_set_width,
    mincutrule_set_within_cut_dist,
    mincutrule_set_within_cut_dist_valid,
    minsteprule_set_concave_corner,
    minsteprule_set_convex_corner,
    minsteprule_set_eol_width,
    minsteprule_set_except_rectangle,
    minsteprule_set_except_same_corners,
    minsteprule_set_max_edges,
    minsteprule_set_max_edges_valid,
    minsteprule_set_min_adj_length1,
    minsteprule_set_min_adj_length1_valid,
    minsteprule_set_min_adj_length2,
    minsteprule_set_min_adj_length2_valid,
    minsteprule_set_min_between_length,
    minsteprule_set_min_between_length_valid,
    minsteprule_set_min_step_length,
    minsteprule_set_no_adjacent_eol,
    minsteprule_set_no_between_eol,
    modbterm_set_mod_net,
    moditerm_set_mod_net,
    module_set_mod_inst,
    mpin_clear_pin_access,
    mterm_set_mark,
    mterm_set_sig_type,
    ndr_set_hard_spacing,
    ndr_set_min_cuts,
    net_clear_guides,
    net_clear_special,
    net_clear_tracks,
    net_clear_wild_connected,
    net_set1st_cap_node_id,
    net_set1st_r_seg_id,
    net_set_auto_taper,
    net_set_cc_adjust_factor,
    net_set_cc_adjust_order,
    net_set_cc_calib_factor,
    net_set_cc_match_ratio,
    net_set_db_cc,
    net_set_disconnected,
    net_set_do_not_touch,
    net_set_extracted,
    net_set_fixed_bump,
    net_set_gndc_calib_factor,
    net_set_i_oflag,
    net_set_jumpers,
    net_set_mark,
    net_set_mark_1,
    net_set_non_default_rule,
    net_set_r_c_disconnected,
    net_set_r_cgraph,
    net_set_ref_cc,
    net_set_select,
    net_set_sig_type,
    net_set_source_type,
    net_set_special,
    net_set_spef,
    net_set_term_ext_ids,
    net_set_weight,
    net_set_wild_connected,
    net_set_wire_altered,
    net_set_wire_ordered,
    net_set_wire_type,
    net_set_x_talk_class,
    obs_set_effective_width,
    obs_set_except_p_g_nets_obstruction,
    obs_set_fill_obstruction,
    obs_set_is_system_reserved,
    obs_set_min_spacing,
    obs_set_pushed_down,
    obs_set_slot_obstruction,
    pwr_domain_set_group,
    pwr_domain_set_parent,
    pwr_domain_set_top,
    pwr_domain_set_voltage,
    pwr_switch_set_lib_cell,
    pwr_switch_set_out_supply_port,
    pwr_switch_set_power_domain,
    region_set_invalid,
    rseg_set_capacitance,
    rseg_set_coords,
    rseg_set_next,
    rseg_set_resistance,
    rseg_set_source_node,
    rseg_set_target_node,
    sbox_set_via_layer_mask,
    site_set_height,
    site_set_symmetry_r90,
    site_set_symmetry_x,
    site_set_symmetry_y,
    site_set_width,
    spacingeolrule_set_above_valid,
    spacingeolrule_set_all_cuts_valid,
    spacingeolrule_set_below_valid,
    spacingeolrule_set_cut_class,
    spacingeolrule_set_cut_class_valid,
    spacingeolrule_set_cut_spaces_valid,
    spacingeolrule_set_cut_spacing_valid,
    spacingeolrule_set_cut_to_metal_space,
    spacingeolrule_set_enclose_cut_valid,
    spacingeolrule_set_enclose_dist,
    spacingeolrule_set_enclosure_end_valid,
    spacingeolrule_set_enclosure_end_width,
    spacingeolrule_set_enclosure_end_within,
    spacingeolrule_set_enclosure_end_within_valid,
    spacingeolrule_set_end_prl,
    spacingeolrule_set_end_prl_space,
    spacingeolrule_set_end_prl_spacing_valid,
    spacingeolrule_set_end_to_end_space,
    spacingeolrule_set_end_to_end_valid,
    spacingeolrule_set_eol_space,
    spacingeolrule_set_eol_width,
    spacingeolrule_set_eol_within,
    spacingeolrule_set_equal_rect_width_valid,
    spacingeolrule_set_exact_width,
    spacingeolrule_set_exact_width_valid,
    spacingeolrule_set_except_exact_width_valid,
    spacingeolrule_set_extension,
    spacingeolrule_set_extension_valid,
    spacingeolrule_set_fill_concave_corner_valid,
    spacingeolrule_set_fill_triangle,
    spacingeolrule_set_max_length,
    spacingeolrule_set_max_length_valid,
    spacingeolrule_set_min_adj_length,
    spacingeolrule_set_min_adj_length1,
    spacingeolrule_set_min_adj_length2,
    spacingeolrule_set_min_adjacent_length_valid,
    spacingeolrule_set_min_length,
    spacingeolrule_set_min_length_valid,
    spacingeolrule_set_non_eol_corner_only_valid,
    spacingeolrule_set_notch_length,
    spacingeolrule_set_one_cut_space,
    spacingeolrule_set_opposite_width,
    spacingeolrule_set_opposite_width_valid,
    spacingeolrule_set_other_end_width,
    spacingeolrule_set_other_end_width_valid,
    spacingeolrule_set_other_width,
    spacingeolrule_set_par_min_length,
    spacingeolrule_set_par_min_length_valid,
    spacingeolrule_set_par_prl,
    spacingeolrule_set_par_prl_valid,
    spacingeolrule_set_par_space,
    spacingeolrule_set_par_within,
    spacingeolrule_set_parallel_edge_valid,
    spacingeolrule_set_parallel_same_mask_valid,
    spacingeolrule_set_prl_valid,
    spacingeolrule_set_same_mask_valid,
    spacingeolrule_set_same_metal_valid,
    spacingeolrule_set_subtract_eol_width_valid,
    spacingeolrule_set_to_concave_corner_valid,
    spacingeolrule_set_to_notch_length_valid,
    spacingeolrule_set_two_cut_space,
    spacingeolrule_set_two_edges_valid,
    spacingeolrule_set_two_min_adj_length_valid,
    spacingeolrule_set_two_sides_valid,
    spacingeolrule_set_with_cut_above_valid,
    spacingeolrule_set_with_cut_space,
    spacingeolrule_set_withcut_valid,
    spacingeolrule_set_within_valid,
    spacingeolrule_set_wrong_dir_extension,
    spacingeolrule_set_wrong_dir_extension_valid,
    spacingeolrule_set_wrong_dir_space,
    spacingeolrule_set_wrong_dir_spacing_valid,
    spacingeolrule_set_wrong_dir_within,
    spacingeolrule_set_wrong_dir_within_valid,
    swire_set_wire_type,
    tech_set_lef_units,
    tech_set_lef_version,
    tech_set_manufacturing_grid,
    techvia_set_default,
    techvia_set_pattern,
    techvia_set_resistance,
    techvia_set_top_of_stack,
    techvialayerrule_set_enclosure,
    techvialayerrule_set_metal_overhang,
    techvialayerrule_set_overhang,
    techvialayerrule_set_resistance,
    techvialayerrule_set_spacing,
    techvialayerrule_set_width,
    twowiresforbiddenrule_set_max_exact_span_length,
    twowiresforbiddenrule_set_max_spacing,
    twowiresforbiddenrule_set_max_span_length,
    twowiresforbiddenrule_set_min_exact_span_length,
    twowiresforbiddenrule_set_min_spacing,
    twowiresforbiddenrule_set_min_span_length,
    twowiresforbiddenrule_set_prl,
    via_set_pattern,
    widthtablerule_set_orthogonal,
    widthtablerule_set_wrong_direction,
    wire_set_property,
    wrongdirspacingrule_set_length,
    wrongdirspacingrule_set_length_valid,
    wrongdirspacingrule_set_noneol_valid,
    wrongdirspacingrule_set_noneol_width,
    wrongdirspacingrule_set_prl_length,
    wrongdirspacingrule_set_wrongdir_space,
};
