// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
#pragma once
#include "shim.h"

inline std::string gs(rust::Str v) { return std::string(v.data(), v.size()); }
inline odb::dbBlock* gen_block(const OdbDb& h) {
  odb::dbChip* c = h.db->getChip(); return c ? c->getBlock() : nullptr; }
inline odb::dbInst* gen_inst(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findInst(gs(n).c_str()) : nullptr; }
inline odb::dbNet* gen_net(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findNet(gs(n).c_str()) : nullptr; }
inline odb::dbBTerm* gen_bterm(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findBTerm(gs(n).c_str()) : nullptr; }
inline odb::dbMaster* gen_master(const OdbDb& h, rust::Str n) {
  std::string name = gs(n);
  for (odb::dbLib* lib : h.db->getLibs()) { if (auto* m = lib->findMaster(name.c_str())) return m; }
  return nullptr; }
inline odb::dbITerm* gen_iterm(const OdbDb& h, rust::Str inst, rust::Str pin) {
  odb::dbInst* i = gen_inst(h, inst); return i ? i->findITerm(gs(pin).c_str()) : nullptr; }
inline odb::dbMTerm* gen_mterm(const OdbDb& h, rust::Str master, rust::Str term) {
  odb::dbMaster* m = gen_master(h, master); return m ? m->findMTerm(gs(term).c_str()) : nullptr; }
inline odb::dbTechLayer* gen_techlayer(const OdbDb& h, rust::Str n) {
  odb::dbTech* t = h.db->getTech(); return t ? t->findLayer(gs(n).c_str()) : nullptr; }
inline odb::dbRow* gen_row(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr; std::string name = gs(n);
  for (odb::dbRow* r : b->getRows()) { if (r->getName() == name) return r; } return nullptr; }
inline odb::dbVia* gen_via(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findVia(gs(n).c_str()) : nullptr; }
inline odb::dbTechVia* gen_techvia(const OdbDb& h, rust::Str n) {
  odb::dbTech* t = h.db->getTech(); return t ? t->findVia(gs(n).c_str()) : nullptr; }
inline odb::dbTechNonDefaultRule* gen_ndr(const OdbDb& h, rust::Str n) {
  std::string name = gs(n); odb::dbBlock* b = gen_block(h);
  if (b) { if (auto* r = b->findNonDefaultRule(name.c_str())) return r; }
  odb::dbTech* t = h.db->getTech(); return t ? t->findNonDefaultRule(name.c_str()) : nullptr; }
inline odb::dbSite* gen_site(const OdbDb& h, rust::Str n) {
  std::string name = gs(n);
  for (odb::dbLib* lib : h.db->getLibs()) { if (auto* s = lib->findSite(name.c_str())) return s; }
  return nullptr; }
inline odb::dbObstruction* gen_obstruction(const OdbDb& h, std::size_t i) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr;
  std::size_t k = 0; for (odb::dbObstruction* o : b->getObstructions()) { if (k++ == i) return o; }
  return nullptr; }
inline odb::dbSWire* gen_swire(const OdbDb& h, rust::Str net, std::size_t i) {
  odb::dbNet* n = gen_net(h, net); if (!n) return nullptr;
  std::size_t k = 0; for (odb::dbSWire* w : n->getSWires()) { if (k++ == i) return w; } return nullptr; }
inline odb::dbWire* gen_wire(const OdbDb& h, rust::Str net) {
  odb::dbNet* n = gen_net(h, net); return n ? n->getWire() : nullptr; }
inline odb::dbFill* gen_fill(const OdbDb& h, std::size_t i) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr;
  std::size_t k = 0; for (odb::dbFill* f : b->getFills()) { if (k++ == i) return f; } return nullptr; }
inline odb::dbBox* gen_box(const OdbDb& h, std::size_t i) {
  odb::dbObstruction* o = gen_obstruction(h, i); return o ? o->getBBox() : nullptr; }
inline odb::dbModule* gen_module(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findModule(gs(n).c_str()) : nullptr; }
inline odb::dbGroup* gen_group(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findGroup(gs(n).c_str()) : nullptr; }
inline odb::dbRegion* gen_region(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findRegion(gs(n).c_str()) : nullptr; }
inline odb::dbBlockage* gen_blockage(const OdbDb& h, std::size_t i) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr;
  std::size_t k = 0; for (odb::dbBlockage* x : b->getBlockages()) { if (k++ == i) return x; } return nullptr; }
inline odb::dbTrackGrid* gen_trackgrid(const OdbDb& h, std::size_t i) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr;
  std::size_t k = 0; for (odb::dbTrackGrid* x : b->getTrackGrids()) { if (k++ == i) return x; } return nullptr; }
inline odb::dbMarkerCategory* gen_marker_cat(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findMarkerCategory(gs(n).c_str()) : nullptr; }
inline odb::dbMarker* gen_marker(const OdbDb& h, rust::Str cat, std::size_t i) {
  odb::dbMarkerCategory* c = gen_marker_cat(h, cat); if (!c) return nullptr;
  std::size_t k = 0; for (odb::dbMarker* m : c->getMarkers()) { if (k++ == i) return m; } return nullptr; }
inline odb::dbModInst* gen_modinst(const OdbDb& h, rust::Str path) {
  odb::dbBlock* b = gen_block(h); return b ? b->findModInst(gs(path).c_str()) : nullptr; }
inline odb::dbModNet* gen_modnet(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findModNet(gs(n).c_str()) : nullptr; }
inline odb::dbModBTerm* gen_modbterm(const OdbDb& h, rust::Str module, std::size_t i) {
  odb::dbModule* m = gen_module(h, module); if (!m) return nullptr;
  std::size_t k = 0; for (odb::dbModBTerm* t : m->getModBTerms()) { if (k++ == i) return t; } return nullptr; }
inline odb::dbModITerm* gen_moditerm(const OdbDb& h, rust::Str modinst, std::size_t i) {
  odb::dbModInst* mi = gen_modinst(h, modinst); if (!mi) return nullptr;
  std::size_t k = 0; for (odb::dbModITerm* t : mi->getModITerms()) { if (k++ == i) return t; } return nullptr; }
inline odb::dbPowerDomain* gen_pwrdomain(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findPowerDomain(gs(n).c_str()) : nullptr; }
inline odb::dbPowerSwitch* gen_pwrswitch(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findPowerSwitch(gs(n).c_str()) : nullptr; }
inline odb::dbIsolation* gen_isolation(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findIsolation(gs(n).c_str()) : nullptr; }
inline odb::dbLevelShifter* gen_levelshifter(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findLevelShifter(gs(n).c_str()) : nullptr; }
inline odb::dbTech* gen_tech(const OdbDb& h) { return h.db->getTech(); }
inline odb::dbLib* gen_lib(const OdbDb& h, rust::Str n) {
  std::string name = gs(n);
  for (odb::dbLib* l : h.db->getLibs()) { if (l->getName() == name) return l; } return nullptr; }
inline odb::dbCapNode* gen_capnode(const OdbDb& h, std::size_t i) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr;
  std::size_t k = 0; for (odb::dbCapNode* x : b->getCapNodes()) { if (k++ == i) return x; } return nullptr; }
inline odb::dbRSeg* gen_rseg(const OdbDb& h, std::size_t i) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr;
  std::size_t k = 0; for (odb::dbRSeg* x : b->getRSegs()) { if (k++ == i) return x; } return nullptr; }
inline odb::dbCCSeg* gen_ccseg(const OdbDb& h, std::size_t i) {
  odb::dbBlock* b = gen_block(h); if (!b) return nullptr;
  std::size_t k = 0; for (odb::dbCCSeg* x : b->getCCSegs()) { if (k++ == i) return x; } return nullptr; }
inline odb::dbSBox* gen_sbox(const OdbDb& h, rust::Str net, std::size_t swire_i, std::size_t sbox_i) {
  odb::dbSWire* w = gen_swire(h, net, swire_i); if (!w) return nullptr;
  std::size_t k = 0; for (odb::dbSBox* b : w->getWires()) { if (k++ == sbox_i) return b; } return nullptr; }
inline odb::dbBPin* gen_bpin(const OdbDb& h, rust::Str bterm, std::size_t i) {
  odb::dbBTerm* t = gen_bterm(h, bterm); if (!t) return nullptr;
  std::size_t k = 0; for (odb::dbBPin* p : t->getBPins()) { if (k++ == i) return p; } return nullptr; }
inline odb::dbMPin* gen_mpin(const OdbDb& h, rust::Str master, rust::Str term, std::size_t i) {
  odb::dbMTerm* mt = gen_mterm(h, master, term); if (!mt) return nullptr;
  std::size_t k = 0; for (odb::dbMPin* p : mt->getMPins()) { if (k++ == i) return p; } return nullptr; }
inline odb::dbTechViaRule* gen_techviarule(const OdbDb& h, std::size_t i) {
  odb::dbTech* t = h.db->getTech(); if (!t) return nullptr;
  std::size_t k = 0; for (odb::dbTechViaRule* x : t->getViaRules()) { if (k++ == i) return x; } return nullptr; }
inline odb::dbTechViaGenerateRule* gen_techviagenrule(const OdbDb& h, std::size_t i) {
  odb::dbTech* t = h.db->getTech(); if (!t) return nullptr;
  std::size_t k = 0; for (odb::dbTechViaGenerateRule* x : t->getViaGenerateRules()) { if (k++ == i) return x; } return nullptr; }
inline odb::dbTechViaLayerRule* gen_techvialayerrule(const OdbDb& h, std::size_t gen_i, std::size_t layer_i) {
  odb::dbTechViaGenerateRule* g = gen_techviagenrule(h, gen_i); return g ? g->getViaLayerRule(layer_i) : nullptr; }
inline odb::dbTechLayerAntennaRule* gen_layerantenna(const OdbDb& h, rust::Str layer) {
  odb::dbTechLayer* l = gen_techlayer(h, layer); return l ? l->getDefaultAntennaRule() : nullptr; }
inline odb::dbTechAntennaPinModel* gen_antennapinmodel(const OdbDb& h, rust::Str master, rust::Str term) {
  odb::dbMTerm* mt = gen_mterm(h, master, term); return mt ? mt->getDefaultAntennaModel() : nullptr; }
// dbViaParams is a VALUE returned by dbVia::getViaParams(); stash it in a thread-local so the
// existing pointer-based marshalling reuses unchanged (pointer valid until the next call).
inline odb::dbViaParams* gen_via_params(const OdbDb& h, rust::Str via) {
  thread_local odb::dbViaParams vp;
  odb::dbVia* v = gen_via(h, via); if (!v) return nullptr; vp = v->getViaParams(); return &vp; }
// 3D / chiplet. These resolve from h.db directly -- a dbChip sits ABOVE dbBlock, so unlike
// every resolver above they do not route through gen_block(). findChip takes const char*;
// findChipInst takes std::string, hence gs(n) without .c_str().
inline odb::dbChip* gen_chip(const OdbDb& h, rust::Str n) {
  return h.db->findChip(gs(n).c_str()); }
inline odb::dbChipInst* gen_chipinst(const OdbDb& h, rust::Str chip, rust::Str n) {
  odb::dbChip* c = gen_chip(h, chip); return c ? c->findChipInst(gs(n)) : nullptr; }
